### ISSUE TITLE
Exchange arrows should only be visible for non-zero flows

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#104]

**Comment by ThierryOllivero** [comment]
It's not a bug, it's a feature. Always interesting to know between which countries are the exchanges.

**Comment by corradio** [comment]
You mean that even if there is no exchange between two countries, you still want the arrow to appear? I'm not sure I follow.

**Comment by ThierryOllivero** [comment]
Yes, this is what I mean. When no exchange, small and not moving, when exchange, bigger and moving.

**Comment by corradio** [comment]
OK so you are basically saying this issue isn't one, and that we shouldn't do the change I suggested.

![image](https://cloud.githubusercontent.com/assets/1655848/19618799/99af2e72-9854-11e6-9532-ebe27b7325b5.png)

Right now zero flows yield a small arrow without any fill.

**Comment by ThierryOllivero** [comment]
Yes, exactly :)

Le 22 oct. 2016 12:40, "Olivier Corradi" <notifications@github.com> a
écrit :

**Comment by corradio** [comment]
What about the fact that with a zero flow, the direction of the arrow isn't
defined?

**Comment by corradio** [comment]
@ThierryOllivero WDYT? I'd like to fix this soon :) I'm bothered by arrows without a fill. Is looks unprofessional and sketchy to me :(

**Comment by corradio** [comment]
Decided to hide arrows with 0 flow.
