### ISSUE TITLE
Survey

### ISSUE THREAD

**Issue by Pantkowsky** [corradio/electricitymap#113]
I would like to include a link to the survey, which would gather user feedback about the overall user experience with the map. I initially thought about creating another box, devoted exclusively to the survey information as you can see below, although after brief discussion with @corradio I agree it might be too much. Therefore the questions is, should the link to the survey be included in the main "welcome" box, or held in a separate one, like on the attached screenshot ?
![untitled](https://cloud.githubusercontent.com/assets/9194725/20017187/cebe8a36-a2c2-11e6-8807-1e5e10766c43.png)
![untitled1](https://cloud.githubusercontent.com/assets/9194725/20018292/6ee249d6-a2c7-11e6-8892-58cefd74ba56.png)

**Comment by corradio** [comment]
Second looks much better, but lacks visibility.
Maybe you could make the whole sentence clickable as a link, and the text could be changed slightly. @guicoelho might be able to provide some meaningful feedback!
