### ISSUE TITLE
Arrows are not self-explanatory enough

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#115]
I've received several feedback about the what the arrows describe. It seems like people don't read the introductory text. Maybe we need to redesign the arrow and add some tooltip?
The arrow scale also seems to be a problem

**Comment by ThierryOllivero** [comment]
Grmpf. I don't like having to change our map just because some people do not:

- Read the introduction
- Take 3 seconds to think about "What could these arrows be..." 

I mean, we do not have that much text on the page, but still we explain "The blinking arrows represent electricity imports and exports.".

Could making the arrows clickable, with a small pop-up or overlay that says "Electricity exchanges between Country A and Country B : 1500 kW" ? Or just a mouse-over ?

**Comment by corradio** [comment]
I was exactly thinking about a mouse-over. That shows the flow between countries. That should be sufficient!

**Comment by corradio** [comment]
Some insights thanks to the survey:
![image](https://cloud.githubusercontent.com/assets/1655848/20192175/0e9b15c8-a789-11e6-9a01-4ed95bfe0e44.png)

**Comment by Pantkowsky** [comment]
I agree with @ThierryOllivero that the explanation included in the welcome box is enough to explain what the arrows represent. However, the size of them is confusing, as well the colors aren't really self-explanatory. Hovering over them to have a pop-up box with some additional info/explanation could be a good idea.

**Comment by corradio** [comment]
For starters they all have the same size now. We should rethink this though.

**Comment by martindaniel4** [comment]
+1 for tooltips. Also are the arrows color coded according to the level of GHG exported ? 

I think import / export is another layer of information. To quote Ben Shneiderman, we should have `overview first and details on demand`. 

This is actually similar to issue https://github.com/corradio/electricitymap/issues/47. We can add extra layers of info, and let the user show / hide them from the lateral menu : 

- [ ] show / hide solar data
- [ ] show / hide import - export
- [ ] show emissions per capita

**Comment by corradio** [comment]
I'll add a tooltip as a quick fix and then refer to #47 for a more detailed layering system.

**Comment by corradio** [comment]
I've played around with tooltips for both exchanges and countries.
Unfortunately you can't see my mouse pointer when I take screenshots, but this should give you a good idea:
![image](https://cloud.githubusercontent.com/assets/1655848/20300811/1f4c6a66-ab21-11e6-83ed-9a36f680332b.png)
![image](https://cloud.githubusercontent.com/assets/1655848/20300975/cf8d0516-ab21-11e6-8c64-3477c3a793a8.png)

What do you guys think?

**Comment by ThierryOllivero** [comment]
I think the country code for Czech Republic is CZ. 

For the first one, should it be rate or ratio?

The second one is still not explanatory. If people did not understand the arrows between the countries, they will not understand it between country flags. "Write Exports from DE to CZ : ". I know, this is too much text...

**Comment by corradio** [comment]
Discussed on Slack
