### ISSUE TITLE
Add missing capacities

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#121]
- [x] Double check PT
- [x] BE
- [x] GR
- [x] IE
- [x] IT
- [x] PL
- [x] SI
- [ ] SK

**Comment by scottlee120** [comment]
Where can I get the capacity info for this? ENTSOE I guess?

**Comment by corradio** [comment]
yes!

**Comment by corradio** [comment]
@scottlee120 I'm assigning you. Let me know if you need help!

**Comment by scottlee120** [comment]
I have the updated JS on my computer - no data available for SK or IT from ENTSOE (none at all for SK and broken up for IT). Also updated PT with ENTSOE figures
