### ISSUE TITLE
Countries that don't have info

### ISSUE THREAD

**Issue by blue1617** [corradio/electricitymap#125]
I think it would be a good idea to change the title to "EU countries" instead of "European". I am talking about 
"Real-time CO2 emissions of the European electricity production", but I can't see info about Bulgaria, so maybe it's not the best suggestion. 
What I want to say is I tried clicking on some countries and nothing happened, so it would be a nice idea to have a message while hovering, or making it more clear to the user what is it your app offers :)

**Comment by corradio** [comment]
We're actually in the process of adding Bulgaria, stay tuned! cc @Pantkowsky

**Comment by corradio** [comment]
Hi @blue1617. Thanks for the feedback. It's well noted. We added Bulgaria in the meantime :)

Olivier
