### ISSUE TITLE
Prepare mobile web app

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#127]
I was thinking of having two tabs: one with the map (draggable?), the other with the country panel.
We can then easily package it in an iOS/Android app.

**Comment by corradio** [comment]
- [ ] Use emojis to add flags in country dropdown (and drop the imgs)
- [ ] Add two tabs at the bottom

**Comment by corradio** [comment]
@ThierryOllivero what do you think about this?
![image](https://cloud.githubusercontent.com/assets/1655848/20308934/46f7584e-ab46-11e6-9566-e13ed4727b3b.png)
![image](https://cloud.githubusercontent.com/assets/1655848/20308959/621a86f0-ab46-11e6-9bab-cc76ea185b94.png)

**Comment by ThierryOllivero** [comment]
I like the second screen, the first one not that much. 

Reasons:
- Countries are ordered by Country Code, and not Country Name. 
- You will have a hard time showing all 28 countries in one screen if you have a one column-list

Proposition:
- Either reorder by Country name (in English or local language), on 2 columns
- Remove the name, keep only flags, large ones, on 4 columns 
My favorite is the second one :)

**Comment by corradio** [comment]
Two columns w/ caption:
![image](https://cloud.githubusercontent.com/assets/1655848/20310318/c431017a-ab4b-11e6-8e1b-46cdf4375d19.png)

Four columns without caption
![image](https://cloud.githubusercontent.com/assets/1655848/20310347/f0d68934-ab4b-11e6-8fca-8b4800df11a2.png)

**Comment by ThierryOllivero** [comment]
You were right, the first is better. But:
- 5 countries are missing
- Countries are not in the right order
- We should remove the text "This map shows in real-time where your electricity comes from and how much CO2 was emitted to produce it. It takes into account electricity imports and exports of each country." to gain some space. And we are not showing a map on mobile.
- We should remove the feedback text and Twitter / FB logos.

**Comment by corradio** [comment]
Thanks @ThierryOllivero, I've done the changes except removing the logos and text. I've modified them though.
