### ISSUE TITLE
Chrome Mobile - Switching from a country to another

### ISSUE THREAD

**Issue by ThierryOllivero** [corradio/electricitymap#130]
Hello,

I was showing the map on my mobile, when I realized the following: when you get to the landing page, you pick a Country A then the site shows you all the data for Country A. Works fine. 

But then, if you want to show data for Country B, you have to reload the page. Would it be possible to add a dropdown list below the data for Country A, to be able to select country B? 

Thanks,

T.

**Comment by corradio** [comment]
Will be fixed with #127
