### ISSUE TITLE
Add ☀️  sun layer

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#136]
Ongoing progress can be checked here: http://electricitymap.tmrow.co/?wind=false&solar=true

We currently have solar data from the NCEP CFS (http://cfs.ncep.noaa.gov/) model, using the `DSWRF` variable (Downward Short-Wave Radiation Flux).
I am not sure of the variable, and whether or not it represents what we want.
Is anyone willing to take a look at this? CFS also gives us other variables if needed.

@brunolajoie can you help here?

**Comment by corradio** [comment]
Inspiration from https://www.ventusky.com/?p=45.4;7.1;4&l=clouds&w=0xIAb9A9A:
![image](https://cloud.githubusercontent.com/assets/1655848/20344964/4464848a-abf5-11e6-9cb2-ec537fb2c538.png)

**Comment by brunolajoie** [comment]
Ok i'm on it

**Comment by brunolajoie** [comment]
Could you give me more details on where you get the variable DSWRF?

**Comment by corradio** [comment]
Thanks man!
http://rda.ucar.edu/datasets/ds094.0/
http://rda.ucar.edu/datasets/ds094.0/#metadata/grib2.html?_do=y
I think this should be a good starting point.

**Comment by brunolajoie** [comment]
At first sight, a dataset updated every 6 hours will not bring enough value to the electricity map, as PV output variation happens on much smaller timescale. Therefore, both DWSRF dataset and Ventusky cloud cover are too slow for our map. Will investigate further but wanted to have your opinion on that

**Comment by corradio** [comment]
Good point. Actually it's the same problem with wind. I basically
interpolate forecasted data that is updated every 6 hours, but it has 1h
resolution. Given the spatial scales we are operating on I think it's ok
and still brings value.

**Comment by Pantkowsky** [comment]
https://www.windytv.com

@corradio Oli thats the website I've told you about when we talked about diverse filters for the map

maybe it could be an inspiration as well, although its highly similar to ventusky.com. The cool feature is however that you can zoom out as see the globe that you can move around, apart from all the filter layers.

**Comment by brunolajoie** [comment]
It seems that there are several DSWRF dataset here http://rda.ucar.edu/datasets/ds094.0/#metadata/detailed.html?_do=y  
Which one were you using exactly? 
![image](https://cloud.githubusercontent.com/assets/22095643/20395024/cadaed28-ace1-11e6-95da-0f67d3131e05.png)

**Comment by corradio** [comment]
Actually I dug a bit deeper to find you the right references.
The webpage is here: http://nomads.ncep.noaa.gov/txt_descriptions/CFS_doc.shtml and http://cfs.ncep.noaa.gov/
I think the details are here: http://journals.ametsoc.org/doi/pdf/10.1175/2010BAMS3001.1
I download the data from here: http://nomads.ncep.noaa.gov/cgi-bin/filter_cfs_flx.pl?dir=%2Fcfs.20161117%2F00%2F6hrly_grib_01

Hope it makes sense. I haven't had time to look at it so much..

**Comment by corradio** [comment]
@brunolajoie, in order to double check, here's DK's wind power curve:

![image](https://cloud.githubusercontent.com/assets/1655848/20633788/832795c0-b34a-11e6-90f6-655440587553.png)

That's consistent. Then I used solar production timeseries for DK, ES, PT:

![image](https://cloud.githubusercontent.com/assets/1655848/20634045/e02f8a78-b34c-11e6-809f-803903490753.png)

and Portugal's solar power curve with the DSWRF variable:
![image](https://cloud.githubusercontent.com/assets/1655848/20634224/c47f5950-b34e-11e6-8dde-06bad5d4c215.png)

It not sure I understand the DSWRF variable:
![image](https://cloud.githubusercontent.com/assets/1655848/20634244/fe8df8d6-b34e-11e6-9f5e-b7248885a936.png)

@brunolajoie any thoughts?

**Comment by corradio** [comment]
Working on #148 to fix this

**Comment by corradio** [comment]
There's more signal now:
![image](https://cloud.githubusercontent.com/assets/1655848/20644777/aea18c26-b442-11e6-9634-6e876b2f67b6.png)

And the noise probably comes from the low sampling rate we have:
![image](https://cloud.githubusercontent.com/assets/1655848/20644778/c291d4de-b442-11e6-9a44-99c00fc5a01b.png)

However I think the data is good enough now!

**Comment by corradio** [comment]
Added experimental support for solar via http://electricitymap.tmrow.co/?wind=false&solar=true

**Comment by corradio** [comment]
Some experiment:
![image](https://cloud.githubusercontent.com/assets/1655848/20771853/772a5258-b74b-11e6-8373-b53f5ba97d5c.png)

**Comment by corradio** [comment]
Wind + Solar w/ bilinear interpolation:

![image](https://cloud.githubusercontent.com/assets/1655848/20774428/83881cfa-b756-11e6-8b7f-a5b4cde91a8a.png)

**Comment by corradio** [comment]
We still need a distinction to show day/night.
