### ISSUE TITLE
Country flag display bug

### ISSUE THREAD

**Issue by brunolajoie** [corradio/electricitymap#137]
![image](https://cloud.githubusercontent.com/assets/22095643/20342272/150eabc6-abea-11e6-87b6-0959fa4202e7.png)

**Comment by corradio** [comment]
Can you give a bit more background? When did it happen? What browser? Does it still happen?
I can't reproduce the bug right now on Chrome:

![image](https://cloud.githubusercontent.com/assets/1655848/20342359/64f9a1fe-abea-11e6-9823-9dbbedb7a51c.png)

**Comment by brunolajoie** [comment]
me niether :)
