### ISSUE TITLE
Add Feature / Montenegro

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#138]
- [x] Add production
- [x] Add capacity
- [x] Add exchanges

**Comment by corradio** [comment]
@Pantkowsky you are assigned to this one - did you have any success?

**Comment by corradio** [comment]
@rustyb We're getting some issues now with Montenergo, where ENTSOE returns a coal value of 0, which is didn't do a couple of days ago.

![image](https://cloud.githubusercontent.com/assets/1655848/22113452/a66a6cc8-de66-11e6-8415-d3bb64b6b053.png)

Can you help us?

**Comment by rustyb** [comment]
Ah interesting i'll follow up with the folks and see if I can find anything out
