### ISSUE TITLE
Add 2020/2025/2050 goals for Xdeg warming

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#155]

**Comment by corradio** [comment]
@brunolajoie I think this is an easy one and could bring a lot of value. Do you have any knowledge of targets set by EU?

**Comment by brunolajoie** [comment]
There's no "°C target" for EU alone, it's only global and for 2100:  2°C max, 1.5°C prefferably.
As for EU, relevant climate targets are:
- 2020: 20% cut in greenhouse gas emissions compared with 1990 levels
- 2030: 40% cut 
- 2050: 80-95% cut

**Comment by corradio** [comment]
Isn't there any targets set in terms of gCO2/kWh? I think I saw it
somewhere.

**Comment by brunolajoie** [comment]
@ThierryOllivero ?

**Comment by ThierryOllivero** [comment]
Nope, never seen targets set as gCO2/kWh. But I can look for it.

**Comment by corradio** [comment]
Who can we ask?

**Comment by brunolajoie** [comment]
The Shift Project or other think tanks?
Interesting related article here : http://www.eea.europa.eu/data-and-maps/indicators/overview-of-the-electricity-production-2/assessment -->it says, "No Targets have been identified" but i don't know if I read it well. Seems like there are no CO2/kWh official targets

**Comment by tezellis** [comment]
I have not seen any consolidated set of CO2/kWh targets anywhere either, certainly not formal targets. I suspect there will be some individual country projections (I know of some for the UK). One potential option is to look at the projected energy mix for those years (which is more likely to be available for all of the EU) and then calculate the inferred CO2/kWh from those mixes.

**Comment by corradio** [comment]
@brunolajoie can you take the lead on this one?

**Comment by brunolajoie** [comment]
As far as I've seen, there are no mandatory targets for GHG intensity of electricity per country in Europe. 

There are only Renewable Targets, which cannot translate into GHG intensity of electricity.
I'm closing this issue as I don't think we can show such targets on the EMap for all its countries. It could be done in a case by case basis, if some country volontarily give themself such targets.
