### ISSUE TITLE
Add visual cue that a country has been selected

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#156]

**Comment by ThierryOllivero** [comment]
@corradio  Is this issue still relevant?

**Comment by corradio** [comment]
It would be nice to know which country is selected. I haven't found a good way to do it though.

**Comment by GergelyMindler** [comment]
@corradio , @ThierryOllivero  I have a suggestion: change the color and thickness of border of selected country. I think the red color and three times tickness would be good.

**Comment by corradio** [comment]
Take a look at https://github.com/corradio/electricitymap/blob/master/web/app/countrymap.js#L79 and feel free to play around with it!

**Comment by GergelyMindler** [comment]
@corradio Thx but currently the docker issue is blocker for me in the most cases... I triy to do what I can but till the solution of docker volume problem, my possibilities are limited.

**Comment by corradio** [comment]
Screenshot:
![image](https://cloud.githubusercontent.com/assets/1655848/21778206/bc3f4198-d6a2-11e6-988e-2542965ef026.png)
What do you guys think?
@GergelyMindler let's discuss in Slack.

**Comment by GergelyMindler** [comment]
@corradio This seems be good, just the border between Norway and Sweden seems be thinner than the others.

**Comment by corradio** [comment]
Let's re-open if this becomes relevant again
