### ISSUE TITLE
And Switzerland?

### ISSUE THREAD

**Issue by BugRaptor** [corradio/electricitymap#159]
What about Switzerland data?

**Comment by corradio** [comment]
Hello @BugRaptor, this should be fixed with commit https://github.com/corradio/electricitymap/commit/40845ba4ef01fe25ff7e16e32501686182fa490f.
The data is unfortunately always a bit old :/
![image](https://cloud.githubusercontent.com/assets/1655848/21073703/8fb87398-bee6-11e6-8e31-66eac6d80271.png)
