### ISSUE TITLE
Twitter bot

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#161]
Twitter bot that sends every week the amount of CO2 emitted by country and link to the EM

cc @martindaniel4

**Comment by gustavecha** [comment]
Really good idea
Currently in France, a bot inform followers when a power plant is available or not. French only, sorry.
Here you go : http://www.twitter.com/AlertesHTB

**Comment by corradio** [comment]
Closing this as this won't be our focus for now. Anybody's free to build one however!
