### ISSUE TITLE
Consume OpenStreetMap data

### ISSUE THREAD

**Issue by gustavecha** [corradio/electricitymap#168]
OpenStreetMap project (wikipedia like for cartography) maintain a pretty accurate model of power grids and power plants.
https://wiki.openstreetmap.org/wiki/Power
May be a great datasource for permanent infrastructure worldwide.
Things sound simple : if a power plant is missing, just add it :)
If you need knowledge on how to use this ecosystem, please ask !

**Comment by corradio** [comment]
Thanks for the link @gustavecha . I'm adding the resource to #196 and we'll keep it in mind!
