### ISSUE TITLE
Missing interconnections in the Nordics

### ISSUE THREAD

**Issue by Rapio** [corradio/electricitymap#170]
The interconnections between Sweden and Lithuania, Poland, Germany and Norway are missing so is Norway - Netherlands and Finland - Estonia.

Most of this information should be available on ENTSO-e, otherwise you should be able to find it on energinet.dk or maybe Nordpoolspot.com

**Comment by Rapio** [comment]
I can see them now. So maybe they just come and go. It's not related to down times zero flows at least.

**Comment by corradio** [comment]
Actually we hide the flows when they are 0, or when the data is too old. Let me know if you have other questions.
