### ISSUE TITLE
Empty rectangles in country panel (i.e. capacity) are not clearly understood

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#173]
Statements:
- I can't figure out the difference between the filled bar and not filled bar on each country?
- I don't understand the meaning of the different color in the electricity production chart. Why for example in Italy for hydro the colored line marks 2,5GW and the transparent line always for hydro marks 25GW? What's the difference?
- When a country is selected and shown it's data is shown, part of the bar is empty, and sometimes there's negative bars next to labels of neighbouring countries flags. Would be nice if the meaning of both were explained in a short text.

**Comment by ThierryOllivero** [comment]
@corradio : the new Hover function you implemented last week should fix the issue. What do you think? Should we close #173 ?

**Comment by corradio** [comment]
The hover is only of the "filled" part of the rectangle. Maybe we should
add another hover on the "empty" part of the triangle? Or maybe we should
extend the curent hover to the outer rectangle (the capacity rectangle?)
