### ISSUE TITLE
Display CO2 emissions from cars

### ISSUE THREAD

**Issue by B1en** [corradio/electricitymap#181]
I was really interested by your map, i think you were a student at centrale de Paris.
I had an idea about creating a pollution map for CO2 emission for cars since it makes a big percentage. It's a little bit complexe but there are many websites where you can be inspired, and i have many more ideas to develop this proposition.

Please you can find my mail here hamza.benhmimou@polytechniqued.edu.

Sincerely,

**Comment by ThierryOllivero** [comment]
Hello Hamza,

Your idea is good, many thanks for that.

You are right, CO2 emissions from cars are really high, so are PM10 and PM2.5.

Showing it on our map would be quite complex and we want the map to remain about electricity generation and the CO2 impact of such generation.

Nevertheless, it could be a good idea for another project. Based on traffic data, individual car datas, it could be fun. Complicated but fun. 

Do you know about this : http://aqicn.org/map/world/ for instance? 

Best regards,

Thierry

**Comment by corradio** [comment]
Hello Hamza,

Thanks for the interest! As Thierry says, this is really about electricity, but your idea is good. Let us know if you are able to advance on it, and if you have specific questions we can always try to help.
If you're keen on helping us developing the electricity map, join us on slack: http://slack.tmrow.co

Olivier

**Comment by B1en** [comment]
Dear, 

Thanks a lot for your answers guys, Thierry thanks for the map, it seems interesting.
Corradio, i am interested in helping you but are you trying to develop the map, i mean topics like:

Wind influence on C02 emissions from a country to an another.
Carbon storage by forests to show that right now even with trees storing this CO2 emissions, it's not enough...

**Comment by corradio** [comment]
Wind influence is definitely something we'd like to look at.
Let's discuss on slack!
