### ISSUE TITLE
Make the color-scale compatible with color-blindness

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#182]
A couple of ideas:
- Use a scale where brightness can be used regardless of hue
- Replace red or green by blue

**Comment by AliShug** [comment]
I'll second this, I'm only mildly colourblind but the current map is basically unreadable for me. Ideally you would make the colours adjustable, or at least lightness-based.

**Comment by nicorikken** [comment]
Same issue here, the current color scheme makes the map totally unreadable. I suggest to use the blue to red pattern, like:
![](https://i.stack.imgur.com/YGZhJ.jpg)

**Comment by corradio** [comment]
Hi there,

The problem with the blue-> red pattern is that "green" is in the middle,
and it makes sense that we represent low carbon by green.
What about a green -> red scale? (say from 505 to 1000 on your scale)

**Comment by AliShug** [comment]
So there's a couple issues with that, namely that in the common green/red colourblindness (which I have) it's green and red that's the issue, and in the scale given I can't see any significant change in lightness from 415-685. In fact everything from 415-640 looks exactly the same. In my opinion,  you can use any colours you like, as long as there's a *constant and significant gradient* in the lightness value.

**Comment by corradio** [comment]
A quick win is to add an alternative scale with a toggle.
https://twitter.com/ed_hawkins/status/831477129279832064

**Comment by corradio** [comment]
Using colorblind-friendly colorscales from https://bids.github.io/colormap/, implemented at https://github.com/d3/d3-scale#interpolateViridis

# Inferno
![image](https://cloud.githubusercontent.com/assets/1655848/22979783/d65609f6-f397-11e6-93ee-16e9ce3c8f24.png)
# Magma
![image](https://cloud.githubusercontent.com/assets/1655848/22979810/f05d6e16-f397-11e6-934f-853b521b74b1.png)
# Plasma
![image](https://cloud.githubusercontent.com/assets/1655848/22979848/14a10c9c-f398-11e6-952d-4453dc3af47e.png)
# Viridis
![image](https://cloud.githubusercontent.com/assets/1655848/22979880/2b717be6-f398-11e6-9aaa-c3f2d980e85f.png)
# Viridis (truncated scale)
![image](https://cloud.githubusercontent.com/assets/1655848/22979949/5dbac198-f398-11e6-92ae-e1b74f461562.png)

What do people think?
