### ISSUE TITLE
Improve map projection

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#183]
Seen on reddit:
"Iceland is the size of Spain on this map"

**Comment by ThierryOllivero** [comment]
Makes me think of: 

![image](https://cloud.githubusercontent.com/assets/22315693/21304025/c2025f66-c5c2-11e6-98b9-c07625a938bb.png)

**Comment by SpiritQuaddicted** [comment]
Yes, funny image but just noise in an issue here. Please don't post noise.

-----

I would recommend the ETRS89 / ETRS-LAEA (EPSG:3035) projection. It is being used by official EU publications and specifically meant for statistical maps of Europe.

Example: https://maps.omniscale.com/en/openstreetmap/epsg-3035

More information:
http://spatialreference.org/ref/epsg/etrs89-etrs-laea/
https://epsg.io/3035

**Comment by corradio** [comment]
I like your pragmatism @SpiritQuaddicted :)
I think what we need is an area-preserving projection. Currently, mercator is used (also used by Google Maps btw), which is suboptimal.
A list of projections implemented in D3 can be seen here: https://github.com/d3/d3-geo-projection. Unfortunately, ETRS89 is not there :/

**Comment by corradio** [comment]
Here's an implementation using the transverse mercator. It's not EPSG:3035 but it's quite close.
Please re-open if this fix is not enough. Will be live at next push to production.

Before:
![image](https://cloud.githubusercontent.com/assets/1655848/21550326/25ba2460-cdf9-11e6-9f52-2677d77a29d4.png)

After:
![image](https://cloud.githubusercontent.com/assets/1655848/21550307/f2e6e55a-cdf8-11e6-81f5-5408911377d9.png)
