### ISSUE TITLE
History

### ISSUE THREAD

**Issue by choehle** [corradio/electricitymap#186]
Hi,

first of all the electricity map is a great way of making emissions and energy flows transparent. Great work guys!

It would be great to also have a history. There are other tools like energy-charts.de to find interesting scenarios throughout the year. It would be great if I could pick a day and time to show how emissions an energy flows performed to that point in time.

Ciao,
Christian

**Comment by corradio** [comment]
Hi Christian,

Thanks for the interest. I suggest you follow https://github.com/corradio/electricitymap/issues/83 which is the issue we're using to track that feature!

Best,

Olivier

**Comment by ThierryOllivero** [comment]
Hello Christian,

Many thanks for your feedback and your suggestion. We already have an issue number #83 on this topic. We are working on it!

Best regards,

Thierry
