### ISSUE TITLE
Color code countries by ratio of renewable production

### ISSUE THREAD

**Issue by choehle** [corradio/electricitymap#187]
I shared the electricity map with others and we got into interesting discussions. One topic came up very often: **Why is Nuclear Power green?** Of course, it is nearly CO2 free but that is only one side of the medal. There are many people that see nuclear as a potential security risk - so part of the energy transition to renewables is to also get rid of nuclear power (at least here in germany).

As there are very different views on nuclear in society:
Would it be an option to introduce an alternative color coding that shows nuclear in red instead of green? That would set a whole new light on the color distribution.

Thanks,
Christian

**Comment by ThierryOllivero** [comment]
Hello Christian,

Are you talking about the color of nuclear as a fuel, when you select a country? I don't see it as green, I see it as yellow, as in uranium yellow, as seen here:

http://www.y12.doe.gov/sites/default/files/Uranium-color-circles.jpg

Either way, there is no hidden meaning behind the colors of the fuels. Gas is currently shown as red and it's a lot less harmful for the environment than coal for instance, which is the absolute worst and should, for me at least, be the primary thing to get rid of when transitioning to renewables.

Best regards,

Thierry Ollivero

**Comment by ThierryOllivero** [comment]
@corradio : Maybe we can make it more yellow than it is today? Or purple? Or whatever?

**Comment by choehle** [comment]
I'm sorry I didn't express well what i meant to say. The color coding of the source in the production overview of a country is fine.
![image](https://cloud.githubusercontent.com/assets/24650456/21420739/96c3c5aa-c82f-11e6-8f1b-dced8bcca511.png)

What i meant was each country having a co2 dependent color. With this coding, of course, a country with 100% nuclear would look green. 
![image](https://cloud.githubusercontent.com/assets/24650456/21420784/d0d73cfe-c82f-11e6-9138-cfbbb5445a7e.png)

From the point of view of reducing the co2 footprint this is reasonable. But there is also a point of view that says co2 is not the whole picture as energy transition is about getting rid of fossils as well as nukes. So it would be cool to have a map where nukes are not displayed green. But i realise that this is not compatible with displaying as co2 intensity alone.

Instead of modifying colors, would it eventually be an option to add an alternative to "co2 intensity"?
Perhaps this could be a "renewables index" for example from 100% - 0% (renewable share on whole production) with the same color coding from green (100%) to black (0%) with an option to count nukes to renewables or not?

Best regards,
Christian

**Comment by corradio** [comment]
Hi Christian,

Indeed it could make sense to show a renewable ratio. We're currently trying to avoid to have other color codings simply to avoid cluttering the UI.
We're also trying to be as explicit as possible, saying that this map is only showing CO2 - but for now we'll try to keep to that scope.
We're keeping your suggestion in mind, and if we add alternative color codings we'll add the renewable ratio, as I think it makes sense.

Olivier

**Comment by choehle** [comment]
Hi Olivier,

I understand and fully agree: Ease of use should stay upfront.
Again thanks a lot for your great work and for consideration of new ideas :-)

Cheers,
Christian

**Comment by corradio** [comment]
One idea I had was to use a dropdown list for the legend label, which would enable us to switch between different color coding. What do you think @brunolajoie @ThierryOllivero ?

![image](https://cloud.githubusercontent.com/assets/1655848/21459368/d727b926-c93d-11e6-9f1c-82dd81d23046.png)

**Comment by ThierryOllivero** [comment]
What's the objective? Help colorblind or show different type of information than CO2 ?

**Comment by corradio** [comment]
The objective is to show different type of information. Like @choehle 's suggestion about showing renewable %, or @brunolajoie 's idea of showing GHG/capita.

**Comment by ThierryOllivero** [comment]
As explained by @corradio in issue #205, we decided against showing different type of information for the moment. 

This includes: 

- GHG / capita
- Ratio of Renewables
