### ISSUE TITLE
Update Finland Capacities

### ISSUE THREAD

**Issue by brunolajoie** [corradio/electricitymap#188]
![image](https://cloud.githubusercontent.com/assets/22095643/21383056/148fca5a-c764-11e6-81ea-7a52290b417a.png)

**Comment by ThierryOllivero** [comment]
Sweden exports are way too high on this graph.

**Comment by corradio** [comment]
Can someone check the entsoe data and maybe raise the issue with them?

**Comment by corradio** [comment]
Also check: http://www.energinet.dk/DA/El/Sider/Det-nordiske-elsystem.aspx

**Comment by corradio** [comment]
@brunolajoie you can now explore dates in the paste using:
https://electricitymap.tmrow.co/?datetime=2016-11-07T14:00:00Z

**Comment by ThierryOllivero** [comment]
Awww, you picked my birthday.

It's great Oli. Do you think we can display somewhere "You are viewing data as of November 7th" and a button "Back to live data"? Unless it's part of the timeline design...

**Comment by corradio** [comment]
It should be part of the timeline design. This is just a hack to allow us to go back in time.

**Comment by brunolajoie** [comment]
Closed by #342
