### ISSUE TITLE
Wind lines not visible on some browsers

### ISSUE THREAD

**Issue by tobiasseidel** [corradio/electricitymap#189]
on my win10 firefox 50.1.0 the site looks like this:
![screenshot20161221](https://cloud.githubusercontent.com/assets/160075/21385131/a9e29b42-c76d-11e6-8c0e-b56f6171bf5d.png)

Wind lines are missing!

**Comment by tobiasseidel** [comment]
My Console looks like this:
wind Object { forecasts: Array[2] }  bundle.a20f2a100186a3517360.js:1:2113
#1 wind forecast target 16 minutes ago made 4 hours ago  bundle.a20f2a100186a3517360.js:1:2372
#2 wind forecast target in 44 minutes made 4 hours ago  bundle.a20f2a100186a3517360.js:1:2477
FR is missing capacity of biomass  bundle.a20f2a100186a3517360.js:1:5261
BG is missing capacity of solar  bundle.a20f2a100186a3517360.js:1:5261
BG is missing capacity of biomass  bundle.a20f2a100186a3517360.js:1:5261
BG is missing capacity of gas  bundle.a20f2a100186a3517360.js:1:5261
BG is missing capacity of coal  bundle.a20f2a100186a3517360.js:1:5261
BG is missing capacity of oil  bundle.a20f2a100186a3517360.js:1:5261
EE is missing production of solar  bundle.a20f2a100186a3517360.js:1:5178
EE is missing production of biomass  bundle.a20f2a100186a3517360.js:1:5178
EE is missing production of gas  bundle.a20f2a100186a3517360.js:1:5178
EE is missing production of coal  bundle.a20f2a100186a3517360.js:1:5178
EE is missing production of oil  bundle.a20f2a100186a3517360.js:1:5178
EE is missing exchanges  bundle.a20f2a100186a3517360.js:1:5348
AT is missing capacity of nuclear  bundle.a20f2a100186a3517360.js:1:5261
ES is missing capacity of biomass  bundle.a20f2a100186a3517360.js:1:5261
ES is missing capacity of oil  bundle.a20f2a100186a3517360.js:1:5261
LT is missing capacity of nuclear  bundle.a20f2a100186a3517360.js:1:5261
LT is missing capacity of coal  bundle.a20f2a100186a3517360.js:1:5261
RO is missing production of oil  bundle.a20f2a100186a3517360.js:1:5178
DK is missing capacity of oil  bundle.a20f2a100186a3517360.js:1:5261
IT is missing capacity of biomass  bundle.a20f2a100186a3517360.js:1:5261
IT is missing capacity of gas  bundle.a20f2a100186a3517360.js:1:5261
IT is missing capacity of coal  bundle.a20f2a100186a3517360.js:1:5261
IT is missing capacity of oil  bundle.a20f2a100186a3517360.js:1:5261
SE is missing capacity of biomass  bundle.a20f2a100186a3517360.js:1:5261
SE is missing capacity of gas  bundle.a20f2a100186a3517360.js:1:5261
SE is missing capacity of coal  bundle.a20f2a100186a3517360.js:1:5261
SE is missing capacity of oil  bundle.a20f2a100186a3517360.js:1:5261
FI is missing capacity of solar  bundle.a20f2a100186a3517360.js:1:5261
FI is missing capacity of biomass  bundle.a20f2a100186a3517360.js:1:5261
FI is missing capacity of gas  bundle.a20f2a100186a3517360.js:1:5261
FI is missing capacity of coal  bundle.a20f2a100186a3517360.js:1:5261
FI is missing capacity of oil  bundle.a20f2a100186a3517360.js:1:5261
GB is missing capacity of biomass  bundle.a20f2a100186a3517360.js:1:5261
GB is missing capacity of coal  bundle.a20f2a100186a3517360.js:1:5261
GB is missing capacity of oil  bundle.a20f2a100186a3517360.js:1:5261
NL is missing capacity of oil  bundle.a20f2a100186a3517360.js:1:5261
SK is missing capacity of wind  bundle.a20f2a100186a3517360.js:1:5261
SK is missing capacity of solar  bundle.a20f2a100186a3517360.js:1:5261
SK is missing capacity of hydro  bundle.a20f2a100186a3517360.js:1:5261
SK is missing capacity of biomass  bundle.a20f2a100186a3517360.js:1:5261
SK is missing capacity of nuclear  bundle.a20f2a100186a3517360.js:1:5261
SK is missing capacity of gas  bundle.a20f2a100186a3517360.js:1:5261
SK is missing capacity of coal  bundle.a20f2a100186a3517360.js:1:5261
SK is missing capacity of oil  bundle.a20f2a100186a3517360.js:1:5261
LV is missing capacity of solar  bundle.a20f2a100186a3517360.js:1:5261
LV is missing capacity of nuclear  bundle.a20f2a100186a3517360.js:1:5261
LV is missing capacity of coal  bundle.a20f2a100186a3517360.js:1:5261
LV is missing capacity of oil  bundle.a20f2a100186a3517360.js:1:5261
CH is missing capacity of wind  bundle.a20f2a100186a3517360.js:1:5261
CH is missing capacity of solar  bundle.a20f2a100186a3517360.js:1:5261
CH is missing capacity of biomass  bundle.a20f2a100186a3517360.js:1:5261
CH is missing capacity of gas  bundle.a20f2a100186a3517360.js:1:5261
CH is missing capacity of coal  bundle.a20f2a100186a3517360.js:1:5261
CH is missing capacity of oil  bundle.a20f2a100186a3517360.js:1:5261
NO is missing capacity of biomass  bundle.a20f2a100186a3517360.js:1:5261
NO is missing capacity of oil  bundle.a20f2a100186a3517360.js:1:5261
MT has no country definition.  bundle.a20f2a100186a3517360.js:1:5396
countries Object { AL: Object, AT: Object, BE: Object, BG: Object, BA: Object, BY: Object, CH: Object, CZ: Object, DE: Object, DK: Object, 29 weitere… }  bundle.a20f2a100186a3517360.js:1:5444
Missing exchange configuration for IT->MT  bundle.a20f2a100186a3517360.js:1:7489
exchanges Object { AL->GR: Object, AT->CH: Object, AT->CZ: Object, AT->DE: Object, AT->HU: Object, AT->IT: Object, AT->SI: Object, BE->FR: Object, BE->NL: Object, BG->GR: Object, 41 weitere… }  bundle.a20f2a100186a3517360.js:1:7550
TypeError: Argument 1 of Window.requestAnimationFrame is not callable.  bundle.a20f2a100186a3517360.js:20:15177

**Comment by corradio** [comment]
Works with 47.0 on MacOs Sierra. Digging deeper.

**Comment by corradio** [comment]
Also works on 50.1 on MacOs Sierra.

**Comment by corradio** [comment]
Also works on 50.1 on Win10. My best bet is that it's a race condition.
