### ISSUE TITLE
All UI elements should be responsive and adapt to screen sizes

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#197]
Please check on big screens:
- [x] Map size
- [x] Font-size
- [x] Left panel size
- [x] Arrow sizes
- [x] Tooltip
- [x] Scales

TODO:
- [ ] Use `rem` unit for all elements
- [ ] Fix all `svg`
  - They should fill they container using 100% width/height
  - If possible, they should internally use % instead of px (paths & transforms can't be used that way..)
  - Remove the need to redraw on resize for %-based units
  - Use the `clientWidth` property to determine size `onresize`

**Comment by GergelyMindler** [comment]
Here is a screenshot from a 23"-size screen:

![kep](https://cloud.githubusercontent.com/assets/24973489/21741766/a54c0bb0-d4e0-11e6-9639-24cee844bef8.png)

**Comment by GergelyMindler** [comment]
Left panel size seems be good in every country.

**Comment by GergelyMindler** [comment]
Map size seems be good but not zoomable.

**Comment by GergelyMindler** [comment]
Font sizes:
- Header of left panel: 1.6em
- "Tip:": 14px - should repair!

Otherwise, the "Carbon intensity" is black with a dark backround - should change it!

**Comment by GergelyMindler** [comment]
There is one more problem: in this example, there is an information popup after i clicked in a country. But this seems be too small.

![kep](https://cloud.githubusercontent.com/assets/24973489/21751169/fd8d8b72-d5c2-11e6-8d79-f906474d8232.png)

**Comment by GergelyMindler** [comment]
The symbols of wind are missing.

 @corradio - In what kind of browsers do you see it?

**Comment by corradio** [comment]
I've updated the first comment of the issue with your comments.
@GergelyMindler what do you mean with the wind symbols ?

**Comment by GergelyMindler** [comment]
Hm, two problem maybe exist:
* the chars of units (0W, 1W, 10GW, etc) are too small - hardly readable if you see the map in a laptop's screen
* The chars in the right-bottom corner are currently black before a dark background - not well viewable

**Comment by corradio** [comment]
I've created https://github.com/corradio/electricitymap/issues/255 to that end.

**Comment by GergelyMindler** [comment]
@corradio An idea: https://www.windytv.com/?47.573,19.054,6

In similar way, you can animate wind easily. This solution works in FF, in GC and in IE.

**Comment by adrianschlatter** [comment]
iPad air in portrait orientation:

![ipad_portrait](https://cloud.githubusercontent.com/assets/10478149/21954679/868b5f50-da58-11e6-8d7a-f11712883b46.jpg)

**Comment by adrianschlatter** [comment]
iPad air in landscape orientation:

Note that the wind is not blowing the same way as in portrait orientation!

![ipad_landscape](https://cloud.githubusercontent.com/assets/10478149/21954684/a426cf90-da58-11e6-8e4a-dfad83280645.jpg)

**Comment by GergelyMindler** [comment]
@corradio I understand why I switched off wind symbols at first time - they cause brokedown after a few minutes in FF :( But they are very slowly in Edge, too.

If you compare it with www.windytv.com, the symbols are too long - maybe this vauses the brokedown.

Other problem that the wind symbols are not so viewable above a country.

**Comment by corradio** [comment]
A screenshot with @brunolajoie 's computer in 1080p:

![image](https://cloud.githubusercontent.com/assets/1655848/22099768/f60ce1aa-de2c-11e6-9d3e-7923139d1144.png)
