### ISSUE TITLE
Invalid IE capacity of wind

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#198]
![image](https://cloud.githubusercontent.com/assets/1655848/21453387/b8bf55a4-c90e-11e6-84a5-997e876c825c.png)

Wind power capacity is too small

**Comment by ThierryOllivero** [comment]
@corradio : 

As of 2015, the capacity was 3025 MW

http://www.iwea.com/index.cfm/page/windenergyfaqs?#q21
