### ISSUE TITLE
Add wholesale and retail electricity price

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#2]

**Comment by ThierryOllivero** [comment]
@corradio: Could you give a few details on what you expect here? Live data? Average data? Actual prices or production costs? Thanks!

**Comment by corradio** [comment]
I was thinking real-time prices but it requires a bit more thinking because there's several markets.
The real question is rather: would it make sense to show any kind of price on this map?

**Comment by ThierryOllivero** [comment]
That's a good question. 

The point of the map is to show real-time impact on climate of electricity production. Prices are not linked to CO2 emissions. Decision to use one production capacity or another is based neither on CO2 emissions nor on prices. 

Showing solar data is interesting to show the impact on PV production. 
Showing wind data is interesting to show the impact on Wind production + CO2 dispersion across Europe. 

Showing prices... Does not fit with the "statement" of the map (not sure if I'm clear). Too much information can have a negative impact on the user experience of "playing with the map."

Maybe a good idea for another Lab ? :)

**Comment by corradio** [comment]
Indeed. Actually I think this issue is not relevant anymore.. so.. closing ;-)
