### ISSUE TITLE
Mobile version no longer working since last update

### ISSUE THREAD

**Issue by ThierryOllivero** [corradio/electricitymap#201]
Hello,

It seems like the Mobile version no longer works since adding the checkbox for Wind.

See attachment for Chrome on Android.

Thierry
![screenshot_20161224-070358](https://cloud.githubusercontent.com/assets/22315693/21465543/b658ccfc-c9a7-11e6-9ce6-4b61b1be83ca.png)

**Comment by ThierryOllivero** [comment]
Hmmm. Cannot reproduce the bug. But found another one.

When on mobile mode, putting the phone in landscape mode changes from mobile to desktop, with only the checkbox for wind. See attachment.
![screenshot_20161224-071201](https://cloud.githubusercontent.com/assets/22315693/21465551/81612868-c9a8-11e6-9a22-97516e1da25a.png)

**Comment by corradio** [comment]
What device are you using? What is the screen size?

**Comment by ThierryOllivero** [comment]
OnePlusOne. Full HD. 5"

On a side note, tried on a Samsung Galaxy Tab. Directly detects it is a tablet and move to Desktop mode. Works fine, even the hover stuff you implemented yesterday. 

Not working : wind and arrow animation.

**Comment by corradio** [comment]
- [x] Mobile mode should be detected even for larger handheld devices
- [ ] Tablet mode should be consistent (don't show the wind toggle if wind is not supported)

**Comment by corradio** [comment]
Should be fixed - pushing in production

**Comment by ThierryOllivero** [comment]
Thanks oli !
