### ISSUE TITLE
Add a "Reddit this" button

### ISSUE THREAD

**Issue by ThierryOllivero** [corradio/electricitymap#204]
Hello,

Given the success of the map on Reddit, I think it could be good to add a button to share the map on Reddit, next to FB, Twitter and Slack.

Example of code : 

`<a href="//www.reddit.com/submit" onclick="window.location = '//www.reddit.com/submit?url=' + encodeURIComponent(window.location); return false"> <img src="//www.redditstatic.com/spreddit10.gif" alt="submit to reddit" border="0" /> </a>
`

**Comment by corradio** [comment]
Discussed on Slack - we won't do it because it will clutter the UI and the gain is minimal.
