### ISSUE TITLE
Add market price data on the map (quick win)

### ISSUE THREAD

**Issue by brunolajoie** [corradio/electricitymap#205]
A quick win could be to add a button to show/hide spot market price data, coloring countries from white (0€/MWh) to red (like 200€/MWh maybe). 

Some data is already available here http://www.rte-france.com/en/eco2mix/donnees-de-marche-en

**Comment by corradio** [comment]
We need to have a discussion about coloring the map with different dimensions:
- % renewable
- price
- amount of wind/solar
- CO2/capita

Up to now we've concluded that it did not make sense as the map was aimed at CO2. Let's discuss this at our next internal meeting.

**Comment by corradio** [comment]
We discussed internally that we'd keep the map color as is, however, I think it would make sense to show a bit more detail in the country panel, such as the spot price.
We could highlight the fact that prices are negative in Denmark when there's a lot of wind.
ENTSOE has an api for spot prices. Here's a TODO:

- [ ] Fetch and store spot prices from ENTSOE
- [ ] Display spot prices

**Comment by ThierryOllivero** [comment]
@Pantkowsky being back with a bit of time on his hands, he will look into it.

Right now we have only day-ahead prices on ENTSO-E. Is this acceptable @brunolajoie?

**Comment by corradio** [comment]
Let's show the current day-ahead price. This makes total sense. Later on we can add balancing costs!

**Comment by brunolajoie** [comment]
Yes, I think day ahead makes sense. Balancing cost will be interesting to see though! but it's more complex to display, as there are many types of balancing reserves!

**Comment by nikkozzblu** [comment]
Hi Guys
Love this project and the visualization you made so far.
Being quite newbi in both Python, node.js and Mongo but willing to contribute, I started with trying to progress that issue.
So far I ve been implementing the Python part in https://github.com/nikkozzblu/electricitymap (might not be optimal way but again I am just starting with Mongo)

I am still stuck on correctly using webpack with node in development but once solved I d like to start working on the visualization. Did you had anything in mind aside including it in each country summary ?

**Comment by corradio** [comment]
Hey @nikkozzblu 

Thanks pretty cool! 
Let's start by grabbing the data and put it in the database, then we add the ENTSOE parser to get a lot more countries, and then we display it.
Can you submit a Pull Request with your changes?
Then I can review it and we can start getting RTE data and showing it!

Thanks for the help. If you want to chat, join us at http://slack.tmrow.co

Oli

**Comment by ThierryOllivero** [comment]
@corradio : are we displaying or only fetching?

**Comment by corradio** [comment]
Here's the result:

![image](https://cloud.githubusercontent.com/assets/1655848/22181418/57169ec6-e08c-11e6-8d24-7bcf554a235a.png)

I still think a visual cue to whether or not this is low/high would be nice. Maybe an indicator as in yelp/google maps where they display '$' when the restaurant is cheap, and '$$$' when it's expensive?

**Comment by nikkozzblu** [comment]
Few issues on this one, 
* Some mapping are wrong due to fact the country expose various prices (by zones)
![image](https://cloud.githubusercontent.com/assets/16333051/22182591/2498c646-e0a9-11e6-816a-91065f3ba993.png)

* Romanian prices are in RON / MWh

**Comment by corradio** [comment]
Indeed you are right. I quickly added a currency check (all non-EUR values will be ignored).
For the zones vs country granularity, this was expected. I don't think there's an easy fix for now.

**Comment by nikkozzblu** [comment]
We can at least use RTE parser for DE, IT,

**Comment by corradio** [comment]
It's dangerous. RTE only considers the neighboring bidding zone for DE for
example. ENTSOE has both bidding zones, and the west one has data but not
the east.

[image: Inline image 1]

**Comment by ThierryOllivero** [comment]
> I still think a visual cue to whether or not this is low/high would be nice. Maybe an indicator as in yelp/google maps where they display '$' when the restaurant is cheap, and '$$$' when it's expensive?

What about a third filter in addition to Solar / Wind, that would remove the colors of countries and show a scale from light blue to dark blue, light blue being low prices and dark blue high prices, or something like that?

BTW, I love it as it is right now, despite some "?" in germany for instance.

**Comment by corradio** [comment]
We've discussed quite vividly the coloring with respect to other values, and I still think we should be very cautious. I'd prefer thinking of a symbol that shows if the price is high or low, because right now it's just a number, hard to understand

**Comment by nikkozzblu** [comment]
![image](https://cloud.githubusercontent.com/assets/16333051/22194946/a69bb350-e145-11e6-8560-506c72b1bf4a.png)

This is the kind of layer (that could be on/off) I had in mind with price. 
If we make the area of the circle proportional to the total production it should be able to fit even in smaller countries (maybe with some reading issue though, to be tested)

**Comment by corradio** [comment]
I like the idea. How would it work for really small countries (Slovenia, Northern Ireland)?
Is the color proportional to the price? We need to find a colorscheme that doesn't conflict with the co2 one.

However: this map is about co2, and the factors that drive it. Therefore, we added the solar/wind layers, as more wind/solar reduces co2. Do prices directly drive co2? I'm a bit afraid that showing prices on the map itself might be a stretch, and we might compromise on readability. I'll think a bit more about it.

Another idea is to upgrade the current text, which is a bit boring:
![image](https://cloud.githubusercontent.com/assets/1655848/22195453/53ca154c-e148-11e6-9358-a400f1f65d7b.png)
to something where the number itself is within a arc/circle which changes based on the price, a bit like on the apple watch:

![image](https://cloud.githubusercontent.com/assets/1655848/22195506/a649f1b6-e148-11e6-8b5f-704a7d0fd26d.png)

But here I am afraid the circular layout is not adapted to a number that can have 3 digits. Else we could also do something more horizontal, as for example showing repeated symbols ('$' vs '$$$', or bars, or a gauge [----_]).
