### ISSUE TITLE
Austria's stated wind capacity lower than production

### ISSUE THREAD

**Issue by kommen** [corradio/electricitymap#206]
Right now the graph for Austria indicates less capacity for wind than reportedly produced, if I interpret it correctly.

<img width="362" alt="screen shot 2016-12-27 at 12 41 37" src="https://cloud.githubusercontent.com/assets/258/21499051/a425b1ac-cc32-11e6-9aad-ffe2be2d8e0f.png">

Thanks for that awesome project!

**Comment by corradio** [comment]
Thanks for raising the issue @kommen, do you have any clue as to where we'd have updated data?
cc @ThierryOllivero ?

**Comment by ThierryOllivero** [comment]
We need to check. Are we using the ENTSO-E API for that ? I saw a similar problem for gas in France.

**Comment by corradio** [comment]
Check the README to see which for which countries we use ENTSOE data. We
never use the api directly though.

**Comment by ThierryOllivero** [comment]
I'll do a deep analysis of it next week and update all. Btw, on the Hover functionnality, could you extend it to the empty part of the bar ?

**Comment by corradio** [comment]
Hover was fixed in https://github.com/corradio/electricitymap/commit/2dd8d7b1bed400324e40a5753d84db09e43bac7c (not pushed to production yet).

**Comment by kommen** [comment]
@corradio IG Windkraft reports the currently installed wind capacity for Austria with 2.556 MW. See https://www.igwindkraft.at on the top right. Unfortunately, I couldn't find it in a machine-readable/query-able form somewhere.

**Comment by ThierryOllivero** [comment]
Thank you Dieter, I'll sure use it !
