### ISSUE TITLE
Lagging after a while

### ISSUE THREAD

**Issue by chrisfoulon** [corradio/electricitymap#207]
Hi, your website is so cool ! 

But I have the feeling that, longer we stay on the page, slower is the animation, like a decrease of frame rate after a moment. I stayed on the page several minutes and let it in background and when I came back the animation was practically frozen. 
Unfortunatly, I have no idea where it could comes from. PS : I'm using Chrome on Windows 10. 

Thanks for your work,

Chris.

**Comment by corradio** [comment]
Hi @chrisfoulon ,

Thanks for the tip. Indeed I have noticed the same. An issue was already opened so let's use that one instead: #184
