### ISSUE TITLE
Small bug for Southern part of the map

### ISSUE THREAD

**Issue by Anozzi** [corradio/electricitymap#208]
thanks a lot for this map, it is amazing!
Just fyi I think there is a small bug for Greece and the southern parts of Albania, Italy, Spain and Portugal where sometimes/most of the times it is not possible to click on the countries and/or view the country information when hovering above it with the cursor.

**Comment by corradio** [comment]
Thanks for finding the bug. I'm on it.

**Comment by corradio** [comment]
Will be fixed at next push to production!
