### ISSUE TITLE
spain production data

### ISSUE THREAD

**Issue by aagm** [corradio/electricitymap#211]
Hi! 
Spain has a lot of data related production consumption  here https://www.esios.ree.es/en/generation-and-consumption  the api for it is in here https://api.esios.ree.es/

**Comment by corradio** [comment]
Hello!
We were actually using REE's API before ENTSOE, and it worked very well.
For now ENTSOE works better, as I remember we had some better data compared to REE.
Feel free to re-open if you believe we should consider REE instead of ENTSOE.

Olivier
