### ISSUE TITLE
Solar layer looks different on different browsers or operating systems

### ISSUE THREAD

**Issue by tobiasseidel** [corradio/electricitymap#213]
It was observed, that the solar radiation layer has a different appearance on different browsers.
Left is Chrome and right is Firefox on Windows 10
![screenshot](https://cloud.githubusercontent.com/assets/160075/21528765/3499e16a-cd35-11e6-8e8f-22c466273756.png)

**Comment by tobiasseidel** [comment]
On my android tablet, Firefox and Chrome crash when I switch on the solar layer!

**Comment by corradio** [comment]
That's not good :(
On Chrome desktop, do you have any errors in the console? If you scroll the
whole way up?
For the tablet, can you try to look at the console for anything suspicious?
You can use the Chrome Remote Debugging interface (
https://developers.google.com/web/tools/chrome-devtools/remote-debugging/)

**Comment by corradio** [comment]
Hey @tobiasseidel , follow up: I fixed a bug through https://github.com/corradio/electricitymap/commit/d9a550fba3c1527bdcabfd99ab24992473f4486d, can you check that the error is still happening, and if it is, check my previous comment about collecting more info?

**Comment by GergelyMindler** [comment]
I have Internet Explorer Edge - here is the same. And here I am able to emulate a lot of another browser: in  Win 10 Mobile, this app gives a white screen.

**Comment by corradio** [comment]
@GergelyMindler can you post screenshots and post console output?
@tobiasseidel is the error still occurring with the fix?

**Comment by corradio** [comment]
It seems to be related to this issue: http://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element

**Comment by GergelyMindler** [comment]
@corradio Here is a screenshot from Edge meanwhile it emulates Win10 mobile:
![image](https://cloud.githubusercontent.com/assets/24973489/21780168/da2fd4bc-d6aa-11e6-8003-5eace25801af.png)

**Comment by corradio** [comment]
@GergelyMindler wow! This however is a different issue that the one discussed here. Can you create a new one if you experience problems on Win10 mobile?

**Comment by corradio** [comment]
Closing this. Please re-open if it keeps happening
