### ISSUE TITLE
carbon intensity for hydro is probably wrong

### ISSUE THREAD

**Issue by v92** [corradio/electricitymap#214]
Hi,
according wikipedia, there is carbon intensity of hydro 4 gCO2/kWh, on map there is 24 gCO2/kWh . Isn't that typo ?

https://en.wikipedia.org/wiki/Emission_intensity

**Comment by corradio** [comment]
Hi @v92 ,

That's the IPCC 2011 value. We're using the 2014 values:
https://en.wikipedia.org/wiki/Life-cycle_greenhouse-gas_emissions_of_energy_sources#2014_IPCC.2C_Global_warming_potential_of_selected_electricity_sources

Feel free to reopen if you have more questions!
