### ISSUE TITLE
The CO2 legend line can't be viewed on the black part of the bar because it's also black

### ISSUE THREAD

**Issue by ric2b** [corradio/electricitymap#217]
The suggested change on pull request https://github.com/corradio/electricitymap/pull/216:

How it looks currently, with a black line:
![untitled](https://cloud.githubusercontent.com/assets/8846579/21532226/303d3aac-cd46-11e6-815b-88403c3ed99a.png)

How it looks with a white line:
![untitled](https://cloud.githubusercontent.com/assets/8846579/21532245/5201dc06-cd46-11e6-9bfc-eac27b1c9753.png)

**Comment by ric2b** [comment]
The suggested change on pull request https://github.com/corradio/electricitymap/pull/216:

How it looks with a black line:
![untitled](https://cloud.githubusercontent.com/assets/8846579/21532226/303d3aac-cd46-11e6-815b-88403c3ed99a.png)

How it looks with a white line:
![untitled](https://cloud.githubusercontent.com/assets/8846579/21532245/5201dc06-cd46-11e6-9bfc-eac27b1c9753.png)

**Comment by corradio** [comment]
Thanks for improving this. It will be live at the next deployment.
