### ISSUE TITLE
CO2 intensity for hydropower in Norway 10x too large

### ISSUE THREAD

**Issue by amaurea** [corradio/electricitymap#218]
The CO2 intensity for hydropower used here seems to be based on the 2014 IPCC *median* number, which is 24 g/kWh. However, the actual intensity varies greatly from dam to dam, mostly due to local climate. It is highest in tropical climates due to greater methane production in reservoirs there, and is minimal in cold climates. So one would expect the numbers for Europe in general and Norway in particular to lie towards the lower part of the 1.0 g/kWh to 2200 g/kWh range the IPCC gives. This is backed up by [a study focusing on Norwegian hydropower](http://ostfoldforskning.no/media/1056/734-1.pdf), which finds 1.9 g/kWh for the power station they studied.

This makes the CO2 intensity numbers for Norway in your model 13 times too high, and since Norway uses almost exclusively hydropower, the total CO2 intensity numbers for electricity production for the country should also be more than 10 times too high.

It is probably safe to assume that hydropower in other European countries is also much closer to 2 g/kWh than the 24 g/kWh that's being assumed.

**Comment by brunolajoie** [comment]
Thanks Amaura, I think your datasource is solid. 

We indeed could start refining emissions factors by country but need to fix something in the code first:

Right now, the map displays "IPCC" in the mouse tooltip as shown in the picture below for all countries and all plants. (it's hardcoded in the html). If we start changing the source by country, we will need to start creating a dynamic link between sources and the html code. 
![image](https://cloud.githubusercontent.com/assets/22095643/22465775/a70766c6-e7bd-11e6-9ca7-7900c95c3cde.png)


If you wish to help doing so, feel free to open a new issue about this more generic topic! 
I'm closing this specific issue right now, which is subordinated to the new one.

**Comment by amaurea** [comment]
I can't find the new issue @brunolajoie mentioned on the bugtracker. Do I need to make a new one for this issue not to be forgotten? I think displaying the right source tooltip is important, but not important enough to let that be the bottleneck preventing one from correcting a factor 10 error in emission numbers for hydropower. Together, I think IPCC 2014 and Modahl&Raadal 2015 give a good case for the lower range of IPCC numbers being representative of Hydropower in Norway-like conditions, which should include at least Norway, Iceland and hydropower in the alps. Hence, while per-country number would be best, I think in the interim using 1.9 g/kWh for all of Europe would be a big improvement, and a fixed citation of " IPCC 2014, Modahl&Raadal 2015" could be given for all countries (ideally with a link to both reports, as especially the last one can be hard to find).

**Comment by corradio** [comment]
I'm re-opening because it could make sense to use 1.9 g/kWh for all of Europe. @brunolajoie ?

**Comment by corradio** [comment]
@brunolajoie can you fix this one? Now we have the capability of using per-country emissions, so this should help!

**Comment by brunolajoie** [comment]
Yes, the code structure now allows to fix this.
I agree we should use 1.9g/kWh for Norway. I don't think we can extrapolate to the whole EU without sci paper backing this assumption though

**Comment by brunolajoie** [comment]
Thanks Amuera, i will update the figure for Norway now that the code allows it.

Although I agree with your commentary about Alpine conditions, but i'm not so sure to take the risk to generalize to other countries without having studies to back them up.  What do you think @corradio

**Comment by corradio** [comment]
I don't have a strong opinion on that one. If the paper is applicable to Europe, then let's use it. Else, let's restrict to Norway, but let's keep in mind that there might be biases if a country makes some analysis only applicable for themselves.
I trust your judgment @brunolajoie

**Comment by brunolajoie** [comment]
I have updated Norway, but will keep other countries like this until we got a better vision. 
There is no rush as 2 or 20 does not make a big difference compared with 500-1000 of fossil fuels.
Thanks

**Comment by amaurea** [comment]
I contacted the author of the Norwegian study and asked her if she had data for other countries. Here is a translation of her answer:

----------------------

It's not strange that there are large differences in emissions from hydropower in different countries. There are emissions from construction of infrastructure, operation and inundation (plus distribution). Emissions from infrastructure and operation do not vary much, but emissions from inundation can can vary extremely much based on vegetation, temperature and climate zone. It's there not unnatural that the contribution from inundation is different in for example Norway and Sweden.

The inundation-emissions are also rather uncertain because different methods of estimation may have been used. So there is still need for more research. We have based our data on research by Sintef when it comes to Norwegian conditions (performed in Follsjø, part of the Trollheim power plant).

Our report, which you refer to, is based on analysis of 11 Norwegian hydropower plants. 9 of these were done by us here at Østlandsforskning. By using these as the basis for Norwegian production in general (by weighting reservoir and run-of-the-river plants and 1. and 2. lifecycle), we have arrived at the average value of 2.4 g CO2-equivalent per kWh. This consists of 0.95 g CO2-eq/kWh from infrastructure and operation and 1.44 g CO2-eq/kWh from inundation (a pure reservoir power plant would have gotten the value of 1.9 g CO2-eq/kWh from inundation, in addition to infrastructure and operation). http://ostfoldforskning.no/media/1056/734-1.pdf

We have made EPDs (third party investigations) for thee Norwegian plants. Two of these are part of the Norwegian average we estimated above, while one was analyzed after this report was finished. You can find these EPDs here: Norwegian EPs: http://epd-norge.no/energi/category332.html

* Trollheim (Statkraft) from 2013: Infrastructure and operation: 2.71 g COw-eq/kWh (inundation emissions were not available at the time that report was made, and are therefore not included): http://epd.nsp01cp.nhosp.no/getfile.php/EPDer/Energi/NEPD-010_Trollheim_en.pdf
* E4 (Embretsfoss power plants) from 2013: Infrastructure and operation 2.19 g CO2-eq/kWh (inundation again not available for this plant): http://epd.nsp01cp.nhosp.no/getfile.php/EPDer/Energi/NEPD_168E_Hydroelectricity-from-E4-Power-Station.pdf
* Skjerka (Agder Energi) from 2016: Infrastructure and operation: 0.9 g CO2-eq/kWh. Inundation: 1.8 g CO2-eq/kWh. Total: 2.7 g CO2-eq/kWh. http://epd.nsp01cp.nhosp.no/getfile.php/EPDer/Energi/NEPD-449-300-EN_Hydroelectricity-from-Skjerka-power-station.pdf

Vattenfall in Sweden has also done a fair bit of work on LCA of their hydropower plants. Here are some numbers:
* LCA-report: Infrastructure and operation: 9 g CO2-eq/kWh: https://www.vattenfall.com/en/file/Livscykelanalys_-_Vattenfalls_elproduktion_i_Norden_11336961.pdf [Amaurea note: I think this number includes inundation, based on the explanatory note for Hydropower on page 18].
* Vattenfall EPD (average of 14 Nordic plants): Total 10 g COw-eq/kWh, of which 7.1 g CO2-eq/kWh is due to inundation, and 2.9 g CO2-eq/kWh from infrastructure, operation and distribution: http://gryphon.environdec.com/data/files/6/7470/epd88en_2015-02-15.pdf

As background data we also use LCA-data from the Swiss database Ecoinvent, which also contains data for hydropower. These are based on Swiss data, which was then modified for each country and geography. You can see the average emission for European hydropower production here (table 4, page 12): http://www.reliable-disclosure.org/upload/259-D5.2_Best_Practice_Environmental_Data.pdf

-----------------------

The weighted average CO2-eq/kWh for European hydropower from the last link she provided is 5.8 g CO2-eq/kWh. It should be pretty safe to use this for any European country for which no better data is available.
