### ISSUE TITLE
how to render the wind power?

### ISSUE THREAD

**Issue by dyh333** [corradio/electricitymap#220]
as the title, would you tell how to render the wind power? use d3 or other third lib?

![image](https://cloud.githubusercontent.com/assets/1221313/21535630/b0f43044-cdb2-11e6-8e23-d05024bb7aeb.png)

**Comment by corradio** [comment]
It's actually draw on canvas.
You can check:
- https://github.com/Esri/wind-js
- https://github.com/FreshyLabs/windy

**Comment by dyh333** [comment]
@corradio thanks
