### ISSUE TITLE
"Unknown" category for Estonia can be changed to coal

### ISSUE THREAD

**Issue by rxxk** [corradio/electricitymap#224]

**Comment by corradio** [comment]
Hello,
Do you have any sources we can refer to?
Olivier

**Comment by rxxk** [comment]
Hello, it is actually oil shale:

"Estonia generates over 90% of its power from oil shale"
http://www.easac.org/fileadmin/PDF_s/reports_statements/Study.pdf

Kind regards,
Martin

**Comment by ThierryOllivero** [comment]
@corradio: I had the same comment from Martin B. Still, I think we should keep it as "Unknown", unless reported otherwise by Estonia. The CO2eq/kWh impact would not change since we have a "assumes conventional" policy for "unknown". 

If you agree, please close the issue. 

T.

**Comment by corradio** [comment]
I agree. We tend to be quite conservative with data: only show the category if we're absolutely sure. 90% is not sure enough :)

Olivier
