### ISSUE TITLE
Pressing solar power potential causes loading loop

### ISSUE THREAD

**Issue by tadhgkearney** [corradio/electricitymap#225]
Whenever I press the solar power potential checkbox, the site gets stuck in a continuous loop, I have to clear the cache for me to able to use the website again.

**Comment by corradio** [comment]
Hello and thanks for reporting. What browset/version are you using? On which os? Do you see errors in the developer console?
Thanks,
Oli

**Comment by tadhgkearney** [comment]
Thanks very much, sorry I didn't see your first email

**Comment by corradio** [comment]
Hi @tadhgkearney ,

The bugfix has now been deployed to all container instances. Can you re-check the map and confirm issue is fixed? Else, feel free to re-open.

Olivier

**Comment by tadhgkearney** [comment]
Yup, the bug is fixed
