### ISSUE TITLE
Change worst value colour (black)

### ISSUE THREAD

**Issue by merildev** [corradio/electricitymap#226]
The country with the highest carbon intensity value has a black background, this can be misleading for the user:

![image](https://cloud.githubusercontent.com/assets/5734722/21567753/e42e0b9a-ceae-11e6-96f5-8bec976a2ce2.png)

In this example, the highest value is 671 (black colour) and the second highest value is 569 (dark brown). The difference between them is *only* 102 but the user may think the difference is much higher because of the contrast between the black and dark brown colour.

I would suggest to change the *worst* colour to a dark shade of brown.

**Comment by ThierryOllivero** [comment]
Hello Merildev. Thanks for your suggestion. We had already discussed the point on issue #92 and decided to go for black when most of the electricity comes from coal. I let you give a look at the discussion we had back then.

Best regards,

Thierry

**Comment by corradio** [comment]
I am actually thinking quite a lot about the colorscale, and I will keep your comment in mind.
It would be nice to have a scale that constantly increases in brightness, as discussed in #182
