### ISSUE TITLE
Solar power potential is not working

### ISSUE THREAD

**Issue by Lokymil** [corradio/electricitymap#227]
When I activate the Solar Power Potential a loader appear for 1 minute and then Firefox (latest version) display a pop-up telling a script has crashed.

According to the debugger helper, it appears to be at `ctx.stroke()` line :

`batchDrawColumns(0, 200, function() {
        var ctx = solarCanvas.node().getContext('2d');
        ctx.clearRect(0, 0, parseInt(solarCanvas.attr('width')), parseInt(solarCanvas.attr('height')));
        buckets.forEach(function(d, i) {
            ctx.beginPath()
            rgbaColor = solarColor.range()[i];
            ctx.strokeStyle = d3.rgb(rgbaColor.replace('rgba', 'rgb'));
            ctx.globalAlpha = parseFloat(rgbaColor
                .replace('(', '')
                .replace(')', '')
                .replace('rgba', '')
                .split(', ')[3]);
            d.forEach(function(d) { ctx.rect(d[0], d[1], 1, 1); });
            ctx.stroke();
        });
        buckets = []; // Release memory
        callback(null);
    });`

**Comment by corradio** [comment]
That's a shame. Are you able to send us a console output and the exact error?
Thanks for raising the issue.
Olivier

**Comment by Lokymil** [comment]
I don't know if you change something but now it works.
However, it is still very slow, it takes 30 seconds to 1 minutes to display the changes and my Firefox is blocked during the loading.
If it can help, I'm on Ubuntu 14.0 and using the latest Firefox with ghostery plugin activated.

**Comment by corradio** [comment]
I think the bug was fixed with https://github.com/corradio/electricitymap/issues/225
I've created issue #230 to work on the speed issue. Feel free to subscribe to that one, or to help if you can!
