### ISSUE TITLE
Improve speed of solar layer rendering

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#230]
Ideas:
- Try lower resolution
- Serve images from (tile) server

**Comment by Pantkowsky** [comment]
I see you have already created that issue. After ticking the solar box, the rendering takes few minutes for me, where the website freezes (on a very decent PC).

**Comment by Lokymil** [comment]
Same here with latest Firefox on Ubuntu 14.0 (decent PC, never experimented that before).

**Comment by nikkozzblu** [comment]
Did you tried any pre rendered svg (after weather update) on server side

**Comment by corradio** [comment]
It's actually a canvas that gets rendered. We need to accomodate multiple resolutions.
Therefore it would make sense to render tiles on the server which would also solve the problem of rendering the layer.
If you know a simple way of doing this, I'm all ears.
Else, we could maybe try to lower the resolution?
