### ISSUE TITLE
Diverse views on the map

### ISSUE THREAD

**Issue by Pantkowsky** [corradio/electricitymap#231]
I'm not sure whether it is changed manually, or is randomly set, but the resolution changes from time to time. One time the EM after entering the website will be quite small, whereas next time, it will be zoomed in significantly. I've also noticed that the visual representation is a bit skewed, like on a screenshot attached. Is this intentional ?
![untitled](https://cloud.githubusercontent.com/assets/9194725/21608310/fb42fea2-d1bb-11e6-9b80-6e48511640d2.png)

**Comment by corradio** [comment]
Can you explain exactly what is wrong with the screenshot?
Also, can you post a screenshot of the small / zoomed-in situations you are describing?

**Comment by Pantkowsky** [comment]
it looks like as if you were looking on it from an angle. Shouldnt it be like for example we have in the readme file? 

https://cloud.githubusercontent.com/assets/1655848/20340757/5ada5cf6-abe3-11e6-97c4-e68929b8a135.png

**Comment by corradio** [comment]
This is because we changed map projection, see https://github.com/corradio/electricitymap/issues/183. What about the other bug, about the fact that some times it zooms in?
