### ISSUE TITLE
Incorrect data for Ireland

### ISSUE THREAD

**Issue by Pantkowsky** [corradio/electricitymap#232]
It was mentioned by one of the users that the data for Ireland is incorrect. As it seems, we are showing the data for Ireland and Northern Ireland combined. The data for Ireland only can be found here:

http://smartgriddashboard.eirgrid.com/#roi/co2

**Comment by Pantkowsky** [comment]
Respectively, some of the information about Northern Ireland can be found here:

http://www.soni.ltd.uk/

**Comment by corradio** [comment]
This was fixed by https://github.com/corradio/electricitymap/commit/1c8ae48ee600360549fb5cc37908577a65f199fe, related to https://github.com/corradio/electricitymap/issues/239.
For Northern Ireland, please see https://github.com/corradio/electricitymap/issues/248.
