### ISSUE TITLE
Country panel scale formatting bug

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#235]
![image](https://cloud.githubusercontent.com/assets/1655848/21610311/7f630e24-d1c7-11e6-9605-aa8387471570.png)

**Comment by ThierryOllivero** [comment]
Same for Italy: 

![image](https://cloud.githubusercontent.com/assets/22315693/21611568/a3679f3c-d1cd-11e6-8f6b-7f020a59e682.png)

**Comment by GergelyMindler** [comment]
This problem is in <svg class="country-table" ... > tag. Inside this, in the <g class="thick" ...> tag, in <text...> tag. Where does it get value?

**Comment by corradio** [comment]
Actually it comes from the format rule that D3 uses to draw the legend:
https://github.com/corradio/electricitymap/blob/master/web/app/countrytable.js#L34
According to https://github.com/d3/d3-format, the formatting string `.0s` gives improper significant digits.
Maybe we should change that to `.3s` in order to have 3 significant digits.

**Comment by GergelyMindler** [comment]
Hm, I changed it and would like to commit it but i cannot login with my user and pass. Why?

**Comment by corradio** [comment]
You need to fork the repo, commit the change to your repo and submit a pull request. You are not authorized to directly commit to this repo :)

**Comment by GergelyMindler** [comment]
Hm, my spelling was maybe too loose... The repo is cloned, latest version is pulled and changes are committed. Just i want to push my changes into the remote repository. Here I meet with an authentication window:

![kep](https://cloud.githubusercontent.com/assets/24973489/21751046/b42a7820-d5c0-11e6-9689-c4d3eed13abf.png)

**Comment by GergelyMindler** [comment]
Maybe my username/password combo is not good - ha! I have to use a lot of login data, sorry. Which username do I use in this project?

**Comment by corradio** [comment]
Let's discuss on slack
