### ISSUE TITLE
Ireland / GB / UK

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#239]
Mentioned on twitter by @BenNiblett:

Hi, on your superb Europe electric map, I'm wondering if you show Northern Ireland in Ireland or UK? (words say GB, map shows UK)

**Comment by tezellis** [comment]
In the ENTSOE data is seems the UK is split in to two regions (on is GB, the other NI) so it depends on which data is being pulled as to whether the label should be UK or GB and whether they should be shown as one country or two.

<img width="216" alt="screen shot 2017-01-04 at 21 28 24" src="https://cloud.githubusercontent.com/assets/24923554/21659917/cac04eb0-d2c4-11e6-9aaa-0a46bf04dc25.png">

**Comment by corradio** [comment]
I double checked and what is pulled is `10YGB----------A` (National Grid BZ / CA/ MBA).
If we want to pull NIE we should also pull `10Y1001A1001A016` (NIE CA (SONI, Northern Ireland)).
Fastest fix is to change the map borders to represent GB.
