### ISSUE TITLE
Reference for CO2e values

### ISSUE THREAD

**Issue by tezellis** [corradio/electricitymap#240]
Unless I am missing something, I couldn't find a reference to the CO2e/kWh factors without digging in to the readme file, but the electricity supply data is well referenced within the viewer. Could I suggest including a link to the wiki page that contains the factors within the viewer?

**Comment by ThierryOllivero** [comment]
Hello Tezellis,

Not sure I get your point. When you click on "Source" in the viewer, you reach the Readme.md in which we give the sources for electricity data. Right above in the ReadMe is the source for CO2eq/kWh ratio.

Best regards,

T.

**Comment by tezellis** [comment]
Sorry yes I just tried this in Chrome and I can find it - for some reason in Safari when I click on source it doesn't let me scroll up (I fact I hadn't realised I was in same readme). Apologies.

**Comment by ThierryOllivero** [comment]
No problem, don't worry :)
