### ISSUE TITLE
Tooltip shows incorrect total production

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#241]
![image](https://cloud.githubusercontent.com/assets/1655848/21661482/8ff6ddde-d2d4-11e6-9f06-a84abc29b7a8.png)

**Comment by ThierryOllivero** [comment]
No it  does not. 

I think you look at the map at a very specific time where Total Production was equal to Total Wind Capacity.

Right now it looks like this. Still close, but not the same

![image](https://cloud.githubusercontent.com/assets/22315693/21671632/fb940808-d31c-11e6-9d84-2cba6ce6efea.png)

**Comment by corradio** [comment]
Indeed!
