### ISSUE TITLE
Solar Layer crash

### ISSUE THREAD

**Issue by Pantkowsky** [corradio/electricitymap#242]
One of the user is having this type of issue:

"I would like to send you a feedback about it. When I change to solar potential, all the screen turns on black and not only the web site but all the windows. I have to close everything and restart internet explorer (I use firefox)."

It needs further investigation

**Comment by ThierryOllivero** [comment]
Hello @Pantkowsky 

This issue is, I believe, redundant with #213 #225 #227 and #230 

I think we do not need further issues, #230 should remain the main one. 

Have a nice day,

T.
