### ISSUE TITLE
Bug on French Gaz installed power 

### ISSUE THREAD

**Issue by Grevar** [corradio/electricitymap#244]
Hello,

As you can se on below screenshot :

![image](https://cloud.githubusercontent.com/assets/24959249/21718983/66438eb8-d41b-11e6-8cbd-cd4050aec941.png)

Capacity factor of french gaz seems to be over 100%. This could be due to wrong data about gaz total capacity perhaps.

RTE website gives around 10GW installed gaz power (01/01/2016)
![image](https://cloud.githubusercontent.com/assets/24959249/21719114/378f4e30-d41c-11e6-99c4-bcef28949c6a.png)
But a new gaz plant has been connected to the grid during 2016 (Combined Cycle Power Plant of Bouchain) : 605MWe.

I haven't found where your 6.12GW comes from. But perhaps I'm missing something.
Don't hesitate to ask if my explanations aren't clear enough. I'd gladly help to this project.

Good job bay the way! :+1: 

Have a nice day.
Grégoire.

**Comment by parisenbouteille** [comment]
Not as big a difference, but it is currently the same for nuke in SE 103%.

**Comment by ThierryOllivero** [comment]
Hello Grégoire,

Many thanks for your feedback and for the information on the new plant. We have already identified the problem in issue #222. We will update all capacities soon, this should correct the problem.

Have a very nice day.

Best regards,

Thierry
