### ISSUE TITLE
Error in Italy's graph 

### ISSUE THREAD

**Issue by alicice** [corradio/electricitymap#246]
Hi there, 
I think there is a mistake in the graph describing Italy's energy production. The horizontal units shows indeed the following numbers: 0GW-5GW-10GW-20GW-20GW. Shouldn't the last value increase as well to 30GW or 40GW?

I attach a screenshot for clarity.

Sorry for bothering and keep up the good work!

Best,
Alice

![screen shot 2017-01-08 at 16 28 20](https://cloud.githubusercontent.com/assets/24990451/21751005/2af3f216-d5c0-11e6-9dd1-ea6bfc09001d.jpg)

**Comment by GergelyMindler** [comment]
DUPLICATED - Issue #235 is the same.

**Comment by corradio** [comment]
As @GergelyMindler mentions, please follow #235 as this issue is a duplicate. Thanks for raising the issue nonetheless!
