### ISSUE TITLE
Missing import: UA > HU

### ISSUE THREAD

**Issue by GergelyMindler** [corradio/electricitymap#249]
It seems that this imported electricity is missing from the map. Hungary imported a lot of energy from Ukraine. This is a bug.

**Comment by corradio** [comment]
The data seems to be there in ENTSOE. See https://transparency.entsoe.eu/transmission-domain/physicalFlow/show?name=&defaultValue=true&viewType=TABLE&areaType=BORDER_BZN&atch=false&dateTime.dateTime=08.01.2017+00:00|CET|DAY&border.values=CTY|UA!BZN_BZN|10YUA-WEPS-----0_BZN_BZN|10YHU-MAVIR----U&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)

The only thing in principle is to add the proper UA ENTSOE identifier `ENTSOE.py` and add the proper arrows in `exchangeconfig.js`.

**Comment by GergelyMindler** [comment]
@corradio  Ohoho! That's seems be great! Thank you. Here are some missed data, too.  Not only UA-HU but UA-SK, UA-PL, etc.

**Comment by corradio** [comment]
UA has two bidding zones:

![image](https://cloud.githubusercontent.com/assets/1655848/22681412/5b813948-ed0d-11e6-8e8d-7707cb099d90.png)

Corresponding to two identifiers:

10Y1001A1001A869: Ukraine BZ / CA / MBA
10YUA-WEPS-----0: Ukraine WEPS BZ / CA / MBA

There's import/export data for 10Y1001A1001A869 for the following countries:

- HU
- PL
- RO
- SK

I have added them.
