### ISSUE TITLE
Legends are too small

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#255]
- [x] Legend of axis for power scale in country panel is too small
- [x] CO2 scale, with black text, conflicts with background and is hard to read

**Comment by GergelyMindler** [comment]
DONE - grow up size of unit in legend of axis

**Comment by GergelyMindler** [comment]
DONE - CO2 scale: background, position and fontsize

**Comment by GergelyMindler** [comment]
Ah, I cannot create pull request for this. Why?

**Comment by brunolajoie** [comment]
![image](https://cloud.githubusercontent.com/assets/22095643/21853360/15c970e2-d817-11e6-9e13-bd5a72ac5d5e.png)
