### ISSUE TITLE
Missing 3rd countries imports

### ISSUE THREAD

**Issue by dguzs** [corradio/electricitymap#257]
Hello,
The tool/map is a great idea! Some comments from a power grid engineer working with power markets.
Latvia imports a lot from Estonia with the effect this has on the CO2 balance on power in Latvian grid.
Lithuania imports a great deal of their power from Russia (Kaliningrad) and Belorussia, the flows in real time for whole Baltic area can be for found here: http://www.statnett.no/Kraftsystemet/Data-fra-kraftsystemet/Nordisk-kraftflyt/
While the average CO2 emission of the Belorussia are hard to determine, the Kaliningrad area produces and exports only gas-fired power from a relatively modern power plant, so their CO2 emission are around 500 g/kWh.
The link I have provided also gives you flow on many other connections you have missed, like HVDC cables FI-EE, SE-LT, DK-SE, SE-DE, DK-DE.
Finland imports a lot of power from Russia and that affects their CO2 balance.
Ukraine exports a lot of coal fired power to Hungary and Slovakia (Burshtyn power island), may be the power grid operators of HU and SK would have that information.

Keep up the good work!
BR
Dmitrijs

**Comment by corradio** [comment]
Hello,
I'm working on adding the remaining missing exchanges, with the exception of Ukraine for which we do not have data. Note that the exchanges that are currently 0 are not shown on the map (but they are not missing!).
