### ISSUE TITLE
Data source unclear

### ISSUE THREAD

**Issue by meyerbe** [corradio/electricitymap#264]
Hi
I really like the map. The only important think I am missing is a clear declaration of and link to the source of the data. Is it possible to add that?
Bettina

**Comment by martindaniel4** [comment]
@meyerbe thanks for your comment. 

I personally think that the way we display sources (per country and on top right) is sufficient, but let us know how you would do it better. 

![screen shot 2017-01-11 at 10 35 07 am](https://cloud.githubusercontent.com/assets/695006/21861467/c9b342e6-d7e9-11e6-9c8a-183f98bc1fbd.png)

Link on Github - https://github.com/corradio/electricitymap#real-time-electricity-data-sources

**Comment by meyerbe** [comment]
Hi Martin
Thanks for your reply and I’m sorry for not seeing the link. Since all your data are perfectly available in one single list, why don’t you just put the ’source’ link in the disclaimer in the main legend (below ‚This project is Open Source: contribute on GitHub <https://github.com/corradio/electricitymap#contribute>.‘ etc.)? This way it is directly visible and people wouldn’t miss it out the way I did.

**Comment by martindaniel4** [comment]
I would argue that the data are listed in the Readme available for anyone that looks on the github page and at the country level on the map. 

Closing this now @meyerbe, let's reopen if other folks have similar feedbacks!

**Comment by corradio** [comment]
Let's keep this one I have had multiple feedbacks stating the same thing.
It seems like there's three types of source we should make very clear:
- source of wind/solar
- source of production data
- source of co2 model & parameters
I also think that @meyerbe 's suggestion should be implemented, if it does not clutter too much the interface.

**Comment by corradio** [comment]
I added a line on the disclaimer. Please re-open if this is not enough:

![image](https://cloud.githubusercontent.com/assets/1655848/22240281/aaa8ea14-e21a-11e6-93d9-9d71d87aff2d.png)
