### ISSUE TITLE
[Data Science] Build utils function to access EM data

### ISSUE THREAD

**Issue by martindaniel4** [corradio/electricitymap#265]
Idea here is to build a set of python functions that could let anyone access and use EM data. 

- Data should be retrieve in a `data_frame` format
- User could define countries they want to retrieve (or all countries)
- User could define date (or date range)
- Type of data returned (carbon emissions, wind, solar) 

To do : 

- [x] `def get_exchanges(from, to, resolution_minutes, countries=None)`
- [x] Add a `/exchanges` endpoint and migrate `get_exchanges`
- [x] `def get_production(from, to, resolution_minutes, countries=None)`
- [ ] `def get_consumption(from, to, resolution_minutes, countries=None)`
- [ ] `def get_co2(from, to, resolution_minutes, countries=None)`
- [ ] `def get_wind(datetime)`
- [ ] `def get_solar(datetime)`
- [x] `def get_prices(datetime)` with a ipynb to compare correlation of co2 w/ prices

**Comment by corradio** [comment]
First step: let's try to write the APIs:

```python
def get_exchanges(from, to, resolution_minutes, countries=None)
def get_production(from, to, resolution_minutes, countries=None)
def get_co2(from, to, resolution_minutes, countries=None)
def get_wind(datetime)
def get_solar(datetime)
```

What do you think?

**Comment by martindaniel4** [comment]
@corradio Sorry for my late response here, my Github notifications go directly to trash. I tried for hours to fix this in Gmail. It's so annoying 😱 

I implemented a first pass [here](https://github.com/corradio/electricitymap/compare/martin_ds_python_utils?expand=1#diff-d801d5a256f9625d57d8688f40c6a222R31) (equivalent to your get_production function). 

Could be used like this : 

```python
import utils

data_frame = df_production(['DE','FR'],'2016-12-23','2016-12-24',1440)
``` 

This returns a nice data frame of production data : 

```
  country  production  sources                  timestamp
0      DE         NaN      oil  2016-12-23T00:00:00+00:00
1      DE      7562.0  nuclear  2016-12-23T00:00:00+00:00
2      DE      2828.0      gas  2016-12-23T00:00:00+00:00
3      DE      4229.0  biomass  2016-12-23T00:00:00+00:00
4      DE     19919.0     coal  2016-12-23T00:00:00+00:00
5      DE         0.0    solar  2016-12-23T00:00:00+00:00
6      DE      4752.0  unknown  2016-12-23T00:00:00+00:00
7      DE     13830.0     wind  2016-12-23T00:00:00+00:00
8      DE      1381.0    hydro  2016-12-23T00:00:00+00:00
0      DE         NaN      oil  2016-12-24T00:00:00+00:00
1      DE      7289.0  nuclear  2016-12-24T00:00:00+00:00
2      DE      2149.0      gas  2016-12-24T00:00:00+00:00
3      DE      4226.0  biomass  2016-12-24T00:00:00+00:00
4      DE      9744.0     coal  2016-12-24T00:00:00+00:00
5      DE         0.0    solar  2016-12-24T00:00:00+00:00
6      DE      3412.0  unknown  2016-12-24T00:00:00+00:00
7      DE     26539.0     wind  2016-12-24T00:00:00+00:00
8      DE      1202.0    hydro  2016-12-24T00:00:00+00:00
0      FR       204.0      oil  2016-12-23T00:00:00+00:00
1      FR     48271.0  nuclear  2016-12-23T00:00:00+00:00
2      FR      8233.0      gas  2016-12-23T00:00:00+00:00
3      FR       768.0  biomass  2016-12-23T00:00:00+00:00
4      FR      1465.0     coal  2016-12-23T00:00:00+00:00
5      FR         0.0    solar  2016-12-23T00:00:00+00:00
6      FR      1508.0     wind  2016-12-23T00:00:00+00:00
```

**Comment by martindaniel4** [comment]
@corradio, @brunolajoie trying to design the `get_solar()` function. I have few questions : 

1 - Would that make sense for this function to have parameters `country`, `datetime`? The function would return the total sun exposure on a country territory for a given datetime. Something like : 

```
country|datetime|sun_exposure
----|---|---
DE|2016-01-01|value
DE|2016-01-02|value
FR|2016-01-01|value
FR|2016-01-02|value
```

The other option is to return the raw data (I imagine similar to the [raw GFS file](http://nomads.ncep.noaa.gov/txt_descriptions/GFS_doc.shtml)), but my worry is that it's 1/ big to handle 2/ maybe not super useful in this format. 

2 - I am trying to understand the format of the API response `v1/solar` : 

```json
{
	"forecasts": [{
		"header": {
			"forecastTime": 5,
			"nx": 360,
			"refTime": "2017-01-14T18:00:00+00:00",
			"dx": 1,
			"dy": 1,
			"lo1": 0,
			"la1": 90,
			"ny": 181
		},
		"data": [0, 0, 0, 0, 0, 0, 0, 0, 0]
	}]
}
```

I assume this is the result of [that parser](https://github.com/corradio/electricitymap/blob/master/feeder/parsers/weather.py#L84), but I have trouble understanding each value of `data` here. 

My guess would be that you return the sun exposure for every `lat` `lng` with an interval of [`one degree`](https://github.com/corradio/electricitymap/blob/master/feeder/parsers/weather.py#L9) in the bounding box defined by [`SW` and `NE`](https://github.com/corradio/electricitymap/blob/master/feeder/parsers/weather.py#L10). Is that correct ? If so, what's your origin and how do you iterate ?

**Comment by corradio** [comment]
Here's what I imagine for the api:

```python
get_solar(bounding_box, datetime, interpolation_method)
```

The object returned should be
```
lon|lat|value
```

We should provide a `get_country_bounding_box` method (or dict), and thereafter, people can use the statistic they want (mean, max, median).

Check the javascript code for info about how to iterate:
https://github.com/corradio/electricitymap/blob/master/web/app/grib.js#L24

Also this snippet of code taken from the Wind & Solar ipynb:
```python
def get_measurements(country_code, t, obj):
    # Return list of measurements inside the country
    header_before = obj['forecasts'][0]['wind'][0]['header']
    header_after  = obj['forecasts'][1]['wind'][0]['header']
    t_before = arrow.get(header_before['refTime']).replace(hours=+header_before['forecastTime'])
    t_after  = arrow.get( header_after['refTime']).replace(hours=+header_after['forecastTime'])

    grid_origin = [header_before['lo1'], header_before['la1']]
    grid_delta = [header_before['dx'], header_before['dy']]
    grid_n = [header_before['nx'], header_before['ny']]

    speeds = []
    dswrfs = []
    bb = bounding_boxes[country_code]

    for i in range(grid_n[0]):
        for j in range(grid_n[1]):
            lon = grid_origin[0] + i * grid_delta[0]
            if lon > 180: lon -= 360
            lat = grid_origin[1] - j * grid_delta[1]
            p = j * grid_n[0] + i
            if lon <= bb[0][0] and lat <= bb[0][1] and \
                lon >= bb[1][0] and lat >= bb[1][1]:
                # We're in the box!
                x = (t.timestamp - t_before.timestamp)/(t_after.timestamp - t_before.timestamp)
                if abs(x) > 1: raise Exception('t is outside of bounds!')
                u = obj['forecasts'][0]['wind'][0]['data'][p] * (1-x) + obj['forecasts'][1]['wind'][0]['data'][p] * x
                v = obj['forecasts'][0]['wind'][1]['data'][p] * (1-x) + obj['forecasts'][1]['wind'][1]['data'][p] * x
                s = obj['forecasts'][0]['solar']['data'][p] * (1-x)   + obj['forecasts'][1]['solar']['data'][p] * x

                speeds.append(np.sqrt(u*u + v*v))
                dswrfs.append(s)
    
    return (speeds, dswrfs)
```

**Comment by corradio** [comment]
I took the liberty of adding a todo: creating an ipynb that would work as a tutorial to show examples of the various functions.

**Comment by martindaniel4** [comment]
@corradio - crystal clear thanks. 

Do you store solar / wind data in the DB ? Looking at the [API routes](https://github.com/corradio/electricitymap/blob/master/web/server.js#L328) looks like you are only returning current data. 

Do you prefer using the `fetch_weather` from your feeder as you do in your Ipython Notebook ?

**Comment by martindaniel4** [comment]
Ok looking at the feeder code, I am worried that installing `pygrib` might be a blocker for many folks that want to use our data. 

It's not working on [Windows for instance](https://github.com/jswhit/pygrib/issues/19) and I ran into errors while installing it on MacOSX El Capitan. 

I would like to keep dependencies light to avoid setup problems. 

Let's sync about alternate solutions. Maybe wind / solar weather can be done in a second time.

**Comment by corradio** [comment]
@martindaniel4 the API route also returns old data (see https://github.com/corradio/electricitymap/blob/master/web/server.js#L333).
In order to see how to fetch forecasts, checkout this function: https://github.com/corradio/electricitymap/blob/master/web/app/dataservice.js#L36. Note that in the frontend we fetch two forecasts (the one at the start, and at the end of the current hour), in order to do linear interpolation between both.
The endpoints return JSON. No need for pygrib!

**Comment by martindaniel4** [comment]
Ah did not catch that one.

Alléluia.

**Comment by brunolajoie** [comment]
Hey guys, I have added def get_consumption(from, to, resolution_minutes, countries=None) to the list
ENSTOE provides a "consumption" data per country. It will help us to double check if production + net import = consumption at all time.

**Comment by martindaniel4** [comment]
👍  do we have an endpoint ready in the API for that or do we need to create one?

**Comment by corradio** [comment]
Needs to be created but it's almost a copy of production

**Comment by corradio** [comment]
Closing this one because I think we have most of the stuff we need!
