### ISSUE TITLE
Possible update on solar capacity in PL

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#272]
Seen in Google Forms:

information about the installed PV in Poland (missing on the website currently) can be found here: https://www.ure.gov.pl/pl/rynki-energii/energia-elektryczna/odnawialne-zrodla-ener/potencjal-krajowy-oze/5753,Moc-zainstalowana-MW.html

**Comment by ThierryOllivero** [comment]
Fixed by #284

**Comment by corradio** [comment]
@brunolajoie can you take a look?

**Comment by ThierryOllivero** [comment]
Well mostly look at #285 :)

**Comment by ThierryOllivero** [comment]
Decision to keep ENTSO-E data upon recommandation from @brunolajoie
