### ISSUE TITLE
Black color is often interpreted as missing data

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#280]
I've now heard it quite a few times on Reddit and on the last call I had.
It might be worth switching to a dark red or dark brown color instead of going the whole way to black.

**Comment by Pantkowsky** [comment]
dark brown would be better than dark red I think. However, maybe instead of changing that we could include a better legend description so the user knows without a doubt that the grey color represents missing data ?

**Comment by corradio** [comment]
I think darkbrown does the trick. I don't know where we would put the explanation that grey is missing data, without cluttering the UI too much. What do you think?

**Comment by Pantkowsky** [comment]
I think we could make a button "help" that after clicking it would show a box in the center with further explanation about how to understand the map. There we could include all of the stuff that needs to be explained and users struggle with. That button could be placed in the welcome box, or right below it (up for discussion).

Other solution would be to make a pop up box that would appear as the first thing on the map. Same idea as example above, but it would appear automatically when entering the website.

**Comment by corradio** [comment]
In my experience the help button is never clicked. If people don't understand, they simply leave. We live in a world with a very short attention span, and it is hard to ask people to read explanations and understand things. We need to build things so they are intuitive.
However I like your idea about the pop up box / tutorial. Takes time to make though.

For a pragmatic solution, why don't we switch the black to darkbrown? @Pantkowsky want to do it? It's in `main.js`, simply changing `black on the `co2Color` object to `darkbrown` :)

**Comment by Pantkowsky** [comment]
Ok, we can change it for now. I think however that maybe we could create a separate thread with the pop up box up for further discussion and maybe future implementation.

You've got a fair point regarding the short attention span - I agree. The pop up box at the launch would however force it to be seen. If the user disregards it directly, then nothing changes, however if he doesnt, he will be significantly more educated towards the understanding of the map

**Comment by corradio** [comment]
Sounds good. Are you changing it then?

**Comment by Pantkowsky** [comment]
yeah I'm gonna change it, give me a sec

**Comment by ThierryOllivero** [comment]
The longest sec since it was invented :(
