### ISSUE TITLE
Gordon Taylor

### ISSUE THREAD

**Issue by gortaylor** [corradio/electricitymap#286]
This is a really great project. My issues are intended to be helpful. See www.energypolicy.co.uk
I checked GB at 2017-01-13 17:39, GMT (data for 1 hour before) wind was 8 GW.
Wind Capacity Factor 7.77GW of 13.5GW - 58%. [This is too high even for the best offshore sites, at perhaps 45 or 50%, never mind the whole operating fleet, for which I would expect more like 35%. One, other or both 'input' values must be wrong. However, I have not checked back to the sources].

**Comment by martindaniel4** [comment]
@gortaylor - I am not sure to understand your issue, can you be more precise ? What does -58% mean ? 

Also please provide a meaningful title.

Thanks!

**Comment by ThierryOllivero** [comment]
Dear Mr Taylor, 

Many thanks for the interest you show in our map. I am not sure you understood properly what we call "Capacity Factor". What it means is that out of the 13,5 GW of installed capacity, 7,77 GW were being produced at the time when you look at the map.

If you look at Austria right now, they use almost 90% of their wind capacity:

![image](https://cloud.githubusercontent.com/assets/22315693/21942321/df66772c-d9cc-11e6-9466-23483faff8e8.png)

We are going to change the text for it to be cleared (#284).

Best regards,

Thierry

**Comment by gortaylor** [comment]
Thank you to martindaniel4 and ThierryOllivero.
I agree that at that time the (short-term) Capacity Factor was 7.77/13.5 = 0.575 = 58% (rounded).
For the UK, Total Operational Capacity	14485.25	Energy Produced (MWh/p.a.)	38574800
(See: http://www.renewableuk.com/page/UKWEDhome).
Hence the annual average Capacity Factor (based on the end of year capacity, as opposed to the average for year capacity) is 38574800/(14485.25 MW x 8760 h) = 0.304 = 30.4%.
But I now agree that the short-term capacity factor could be 58%, or possibly higher, especially as in the UK, the wind speeds are higher in winter than in summer, much like the UK electrical demand.
I apologise for raising this issue wrongly, but am a great fan of wind power, and watch out for any over-claiming which could damage it's reputation. I was wrong.

**Comment by martindaniel4** [comment]
Sounds like making things clearer in #284 will help. 

Closing this issue for now. Feel free to open it if needed.
