### ISSUE TITLE
Estonian Oil Shade

### ISSUE THREAD

**Issue by greennuts** [corradio/electricitymap#294]
Hi,
Estonians doesn't have oil, but oil shade electricity stations ans so CO2 calculation is a bit off. Based on this study http://www.easac.eu/fileadmin/PDF_s/reports_statements/Study.pdf the value for gCO2eq/kWh should be around 1771 gCO2eq/kWh. Yeah, it sounds terrible, but that's the math as the efficiency is just around 30%.
106kg CO2 is emitted from GJ direct combustion, so 1GJ is around 277.8kWh, that's give us 577 gCO2eq/kWh.
They can produce 850kWh electricy from 1t of oil shade 
For 1t oil shade they will produce 2613kWh in direct combustion.
2613/850=3.07
3.07*577=1771 gCO2eq/kWh

I hope it helps and it's accurate as I understand.

Oskars

**Comment by ThierryOllivero** [comment]
Hello Oskars,

Many thanks for your feedback. We already have the issue #278 open for this topic (both for shale oil and oil). 

Our scientific authority @brunolajoie will look at it and advise on how to fix the issue. 

Best regards,

Thierry
