### ISSUE TITLE
Filter extension with real-time air quality data 

### ISSUE THREAD

**Issue by Pantkowsky** [corradio/electricitymap#296]
*Up for discussion*

Real-time data showing air quality in the world can be found here:
http://aqicn.org/map/europe/pl/#@g/47.2552/10.0525/6z

It would align well with the current information presented by EM, to actually show the air quality as one of the filters on the map.

What do you think @corradio @ThierryOllivero

**Comment by ThierryOllivero** [comment]
Hey @Pantkowsky 

This is an idea we had already discussed on Slack, I think.

The Electricity Map is showing emissions coming from electricity generation in Europe. We do not show all the emissions coming from other sources, so the correlation with air quality will not be immediate.

The real-time data showing air quality is interesting but the only common points with the EM are:

- it's a map
- it's real time
- it's related to the environment

I personally believe this is not enough to justify merging it with the EM. This could make things quite complicated and I don't see what added value we would bring compared to the aqicn map. 

Furthermore, we want to keep the UI as simple as possible. Adding a new dimension could cloud everything and make us lose focus. 

Keep also in mind that the "level of zoom" are different. On our map, we show countries, maybe in the future individual states in big countries (USA, Canada, Australia, China, you name them), but the air quality is shown device by device. And you cannot really provide an average... Imagine for Poland, averaging data from Kędzierzyn-Koźle and Gdańsk would not make any sense for the rest of the country.

Let's wait for the feedback of @corradio before deciding on the future of this issue. 

Best regards,

Thierry

**Comment by corradio** [comment]
Thanks for the input, but it's out of scope.
Our goal is not to show pollution, but to inform people of where we stand with respect to mitigation of climate change in the electricity sector. Air quality is another topic. Not uninteresting, but not our scope.
