### ISSUE TITLE
The map should show no data if a time in the future is picked

### ISSUE THREAD

**Issue by ThierryOllivero** [corradio/electricitymap#297]
![image](https://cloud.githubusercontent.com/assets/22315693/22009500/f4b9ca7a-dc83-11e6-81c3-6fce79741d8a.png)

Explanation:

- Current (time of the issue) datetime is 2017-01-10T06:00:00Z
- If I enter 2017-01-17T19:00:00Z, it shows me current data (see screen above)
- If I enter 2017-01-18T19:00:00Z, it shows every country in grey (expected behavior)

So it seems like the behavior is OK if you select a date in the future, but not a time, the same day, in the future.

Thierry

**Comment by corradio** [comment]
For a given date, the system searches for any country for which we have data in the last 24h. Therefore, if you pick a country in the next 24h, you should still have data.
We can make this condition stricter if you think. Feel free to reopen if that's the case!

**Comment by ThierryOllivero** [comment]
Sorry, I reopen. I think the condition should be stricter. If you pick a country in the future, you should have no data. Even if the future is in one hour. 

Some people could think that we are showing forecasts if we keep it like that and they select tonight by mistake.

**Comment by corradio** [comment]
If I undestand correctly, when selecting time `t` you would show the latest data for all countries taken after time `max(t - 24h, now())`?

**Comment by ThierryOllivero** [comment]
When selectinf time t, I would show:

'if t>now() , nodata'
'if t<now(), mostrecentdate(t-24h, t)'

**Comment by corradio** [comment]
ok will fix
