### ISSUE TITLE
Carbon intensity versus absolute carbon dioxide emission

### ISSUE THREAD

**Issue by outlying** [corradio/electricitymap#302]
I'm not a specialist on the topic but I was a little surprised that Poland seems the worst when I looked at the map for the first time.

I don't have current data but as of 2014 Germany emitted over 2x more CO2 than Poland
https://en.wikipedia.org/wiki/List_of_countries_by_carbon_dioxide_emissions

Intensity is lower because of other power plant types but the absolute damage is much higher, isn't it?

**Comment by ThierryOllivero** [comment]
Hello outlying, 

True, if we look at the total emissions in terms of tCO2eq/h, Germany is above Poland. 

We have already discussed this point in the following issues: #101 #203 

Regarding absolute damage, not really. It always depend of what we are talking about. Global emissions in the World? Yes, Germany emits more. By inhabitants? Poland emits more. By area? Germany emits more. Etc. Always difficult to choose. 

Thus, carbon intensity is a good way to compare the CO2 impact of technologies used.

Best regards,

Thierry
