### ISSUE TITLE
Pool prices

### ISSUE THREAD

**Issue by jgracio** [corradio/electricitymap#306]
The project is excellent and I'm using it as a favorite page to follow what is going on in Europe.

To complement the so useful information I suggest you include the current pool price in each country.

Thanks again for sharing the project

**Comment by ThierryOllivero** [comment]
Hello jgracio,

Thanks for your feedback and kind message  :)

We already have issue #205 on this topic, so I will close this one.

Best regards,

Thierry

**Comment by jgracio** [comment]
Thanks for the feedback and my apologies for lacking care not going through all previous suggestions.

Can you please share the current development plans for the project?

Regards
José Grácio

Enviado do meu telemóvel


No dia 20/01/2017, às 10:49, Thierry Ollivero <notifications@github.com<mailto:notifications@github.com>> escreveu:


Hello jgracio,

Thanks for your feedback and kind message :)

We already have issue #205<https://github.com/corradio/electricitymap/issues/205> on this topic, so I will close this one.

Best regards,

Thierry

-

**Comment by corradio** [comment]
Hello @jgracio ,

In a nutshell, we want to add some timeseries that show the evolution of the different values, we want to add proper mobile support, and extend the map to more countries (the world!)

Olivier
