### ISSUE TITLE
Exchanges between Albania and Serbia are incorrectly shown

### ISSUE THREAD

**Issue by ThierryOllivero** [corradio/electricitymap#316]
![image](https://cloud.githubusercontent.com/assets/22315693/22284530/072c8cfa-e2e8-11e6-953a-3a8db64dfe77.png)

Albania only exchanges electricity with Greece, Montenegro and Kosovo. The map shows exchanges with Serbia (as stated on ENTSO-E) instead of Kosovo.

Since we are showing both Kosovo and Serbia on the map, we should correct the arrow.

Thierry

**Comment by corradio** [comment]
@rustyb, I think that's also an issue you might want to talk about with your colleagues:

![image](https://cloud.githubusercontent.com/assets/1655848/22281352/db989e50-e2d6-11e6-8ef1-3cedb4685d21.png)

**Comment by ThierryOllivero** [comment]
We have to keep in mind it remains an open political issue. The government of Serbia does not recognize Kosovo as a sovereign state. 

In the EU28, Cyprus, Greece, Romania, Slovakia and Spain dot not recognize it either. 

Therefore I don't know if ENTSO-E can take any position on this matter. 

3 possibilities:

1. We keep it as it is on the map (showing an arrow from Albania to Serbia, and accounting the import-exports values in both countires)
2. We switch the arrow towards Kosovo and change the import-exports values from RS to XK
3. We take a middle-ground, switch the arrow towards Kosovo and keep the accounting of import-exports i n RS.

What do you think @corradio ?

**Comment by corradio** [comment]
If it is not recognised in the EU28, then maybe we should simply merge the two polygons and still show it as part of RS?

**Comment by ThierryOllivero** [comment]
"The EU, like other IGOs, does not possess the legal capacity to diplomatically recognise any state; member states do so individually. The majority of member states have recognised Kosovo. To articulate a common EU policy of either support or opposition to Kosovo's independence would require unanimity on the subject from all 28 member states, which does not presently exist."

So, after discussion with someone well aware of these topics and given your proposition, I think the more politically correct would be to:
[ ] Merge the two polygons
[ ] Show a dashed line border between the two polygons (if possible)
[ ] Show the arrow going towards the Kosovo part
[ ] Explain in the Readme why we take this position

T.

**Comment by corradio** [comment]
@ThierryOllivero what is the status here?
