### ISSUE TITLE
Support prices which are fetched in different currencies

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#317]
Currently, ENTSOE gives some prices in foreign currencies.
We could store them in local currencies and a third party api to do the conversion when shown on the map

**Comment by nikkozzblu** [comment]
Yes I think we should start with storing both price and currency in the price table and display them both (I.e. each price in its own currency)
Second step would be to find a currency exchange API and perform requiered conversions on the client

**Comment by corradio** [comment]
This should do:
- http://openexchangerates.github.io/money.js/
- http://fixer.io/

**Comment by corradio** [comment]
@nikkozzblu do you have time to help here?

**Comment by nikkozzblu** [comment]
Hi, unfortunately not in the coming days, i will try to take a look this week end but can t promise anything

Nico Juguet

-------- Mensaje original --------
Asunto: Re: [corradio/electricitymap] Support prices which are fetched in different currencies (#317)
De: Olivier Corradi
Para: corradio/electricitymap
CC: nikkozzblu ,Mention


@nikkozzblu<https://github.com/nikkozzblu> do you have time to help here?

**Comment by corradio** [comment]
ok - no worries

**Comment by corradio** [comment]
Actually I'll just show the local currency.
