### ISSUE TITLE
tooltip unclear

### ISSUE THREAD

**Issue by brunolajoie** [corradio/electricitymap#322]
I would add the word "consumption" to differentiate it from "capacity".

![untitled](https://cloud.githubusercontent.com/assets/22095643/22339956/0c22696e-e3ec-11e6-8776-9b72b60624da.png)

**Comment by corradio** [comment]
![image](https://cloud.githubusercontent.com/assets/1655848/22363917/119ccaf6-e46e-11e6-92d8-632f2a6a323f.png)
