### ISSUE TITLE
Add GB-NIR capacities

### ISSUE THREAD

**Issue by brunolajoie** [corradio/electricitymap#323]
NIR Capacity (2016) 
Source: http://www.eirgridgroup.com/site-files/library/EirGrid/Generation_Capacity_Statement_20162025_FINAL.pdf

Wind: 863MW
Sun: 77M
Gas: 1004MW
Oil: 415MW
Coal: 764MW
Biomass: 35MW

Interconnector: 450MW 

@oli NIR is not a country its a zone. I don't know how to add capacities to a zone in our code in order to create the corresponding pull request

**Comment by corradio** [comment]
Use the `GB-NIR` zone. For now zones are still called "countryCodes" but it will be changed soon.

**Comment by brunolajoie** [comment]
Ok i'll
- Update the capacities.json with GB-NIR
- Remove GB-NIR capacities from GB
- update readme

**Comment by corradio** [comment]
Double check the GB capacities. If they are from ENTSOE, they probably only count for GB and not UK.

**Comment by brunolajoie** [comment]
Do you confirm that ENSTOE Data for "UK" in https://transparency.entsoe.eu/ is actually "GB" only?

**Comment by corradio** [comment]
If you use the "bidding zone" tab, then yes.

![image](https://cloud.githubusercontent.com/assets/1655848/22342387/81ef355c-e3f4-11e6-93e7-1736916ece6f.png)

Link: https://transparency.entsoe.eu/generation/r2/installedGenerationCapacityAggregation/show?name=&defaultValue=true&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2017+00:00|UTC|YEAR&dateTime.endDateTime=01.01.2017+00:00|UTC|YEAR&area.values=CTY|GB!BZN|10YGB----------A&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19

**Comment by brunolajoie** [comment]
Issue solved in #328
