### ISSUE TITLE
Time-averaged values

### ISSUE THREAD

**Issue by Eirikep** [corradio/electricitymap#324]
Dear Tomorrow team,

Thanks for the awesome web page you have created! It's a brilliant idea that with flawless execution to boot, and I am showing it to everyone that I know. 

However, while most people I introduce it to find it very interesting and enlightening, sometimes people will dismiss the live data for being entirely unrepresentative and therefore mostly irrelevant. To combat this, I thought it'd be great to have an option to display time-averaged data for, say, the last hour, day, week, month, or year. It could simply be a drop down menu that would shift from live view to a map showing constant, time-averaged values over the selected interval. In this way, it would add another dimension to the page by allowing even the most casual user (those that are not checking several times a day, every day of the week) to gain insights in to the longer-term effects of the production mix of the European countries. 

What do you think?

**Comment by martindaniel4** [comment]
@Eirikep thanks for your feedback! Absolutely, we are working on this: 

- We are working on time series at the country level to show historical value in this issue https://github.com/corradio/electricitymap/issues/305
- There is already the possibility to specify a specific datetime by passing a `datetime` parameter like so - https://www.electricitymap.org/?datetime=2016-12-10T14:00:00
- Lastly, we developed a custom API that lets you access data and run your own aggregation, see it here - https://github.com/corradio/electricitymap/tree/master/datascience

**Comment by corradio** [comment]
I wouldn't be able to summarise it more concisely than @martindaniel4 just did. I'm closing this, but feel free to re-open if you're not satisfied with the answer. In any case, we can keep discussing.
