### ISSUE TITLE
great start

### ISSUE THREAD

**Issue by AndyinHawick** [corradio/electricitymap#329]
Thanks for the good map.

It would be interesting to plot on a graph the price & carbon intensity of each country. I realise that both data are not known for every country but where they are, it can supply a point on the graph.

At standard scale, the Tomorrow link was covering the Solar checkbox and I had to zoom the content of the webpage to allow me to select that option.

It would be good to disaggregate Scotland (and Wales?) from England as it has very different carbon aspirations and the generation reflects that.

Well done

**Comment by corradio** [comment]
Thanks @AndyinHawick.
Indeed those things are on our radar. Will be done soon.
In the meantime, you might want to subscribe to this issue: https://github.com/corradio/electricitymap/issues/305
