### ISSUE TITLE
Consumption percentages can add up to more than 100

### ISSUE THREAD

**Issue by samhatfield** [corradio/electricitymap#337]
With exports and storage, the percentages of a country's consumption met by each energy source can add up to more than 100. For example, Portugal at the moment is consuming 4.13GW:

- 3.96GW of wind (96% of consumption)
- 598MW of hydro (14%)
- 324 MW of biomass (8%)
- 876 MW of gas (21%)
- 1.73 GW of coal (42%)
- 38 MW of unknown (1%)

It also exports 2.62GW and is storing 770 MW. I think it makes more sense to show the fraction of production met by each source. Then the percentages would add up to 100.

**Comment by ThierryOllivero** [comment]
Hmmm, true, there is a problem here.

**Comment by corradio** [comment]
We're on it with bruno

**Comment by corradio** [comment]
Hi @samhatfield ,

We've updated the tooltips with a new version. It should be more consistent and easier to read now. Please re-open if you have more questions

**Comment by samhatfield** [comment]
Looks good!
