### ISSUE TITLE
Should cross boundaries exchange be optional layer ?

### ISSUE THREAD

**Issue by nikkozzblu** [corradio/electricitymap#354]
It is nice, but the animation make the map very heavy, might be good to have a check box to disable (as wind and solar, enable by default thought)

**Comment by corradio** [comment]
Yes! @scarlac and me are looking at ways to optimise this, using GIFs for example.
I'm closing this one in favor of #199. If we can't find a way to optimise, we will probably disable animations.

**Comment by nikkozzblu** [comment]
I think it is not only a matter of cpu ressource (for which i am sure gif will do the job). But also from a human being perspective, some might rather look at a static map that make it overall look simpler, so i would still push in favour of a check box control (default checked)

Nico Juguet

-------- Mensaje original --------
Asunto: Re: [corradio/electricitymap] Should cross boundaries exchange be optional layer ? (#354)
De: Olivier Corradi
Para: corradio/electricitymap
CC: nikkozzblu ,Author


Closed #354<https://github.com/corradio/electricitymap/issues/354>.

**Comment by corradio** [comment]
So you're saying there's too much information and that sometimes people
might want to remove arrows?
If we enable it by default I think few people will disable it, so that
might not be the solution.

**Comment by nikkozzblu** [comment]
I think we can treat that as solar and wind, ie with cookie saving user settings, just enabled by default... or maybe even not enable by default... this depends on user feedbacks

Nico Juguet

-------- Mensaje original --------
Asunto: Re: [corradio/electricitymap] Should cross boundaries exchange be optional layer ? (#354)
De: Olivier Corradi
Para: corradio/electricitymap
CC: nikkozzblu ,Author

So you're saying there's too much information and that sometimes people
might want to remove arrows?
If we enable it by default I think few people will disable it, so that
might not be the solution.

**Comment by corradio** [comment]
I'll go through user reviews to see if your feeling is confirmed!
