### ISSUE TITLE
Mozzilla Crash

### ISSUE THREAD

**Issue by A75871** [corradio/electricitymap#355]
Hi,

The problem that I told you on Twiter.
I'm not sure that this upload of files will work. If not tell me by mail and I send them.
PauloJCGFranco@gmail.com

[Uploading Console_Mozilla.txt…]()
![Uploading mozzila.jpg…]()

**Comment by corradio** [comment]
Hey!

It didn't work. I think you have to wait for the "uploading" message to change into a picture link before you actually send the comment. Can you try again? Or send it to hello@tmrow.co

Thanks!

Oli

**Comment by A75871** [comment]
I send it to the email.
I hope it worked now.

**Comment by corradio** [comment]
Closing this one as we have no news. Please comment and we will re-open to investigate!
