### ISSUE TITLE
Old prices are shown

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#365]
#What 
Old prices are shown on the map. For example, click on RO:

![image](https://cloud.githubusercontent.com/assets/1655848/22875332/63a311f6-f1cb-11e6-820c-a88aeff24ae3.png)

cc @martindaniel4

**Comment by nikkozzblu** [comment]
Would that be specific to romania ? Price are rejected as in RON but first few timestamps were imported as if it was EUR ?

Nico Juguet

-------- Mensaje original --------
Asunto: [corradio/electricitymap] Old prices are shown (#365)
De: Olivier Corradi
Para: corradio/electricitymap
CC: Subscribed


#What
Old prices are shown on the map. For example, click on RO:

[image]<https://cloud.githubusercontent.com/assets/1655848/22875332/63a311f6-f1cb-11e6-820c-a88aeff24ae3.png>

cc @martindaniel4<https://github.com/martindaniel4>

**Comment by corradio** [comment]
It's actually old data from before we pushed that fix. But the bug refers to the fact that we shouldn't show data from january on the map! If it's older than 24h it should be ignored.

**Comment by nikkozzblu** [comment]
Ok
