### ISSUE TITLE
[Idea] Display aggregated total imports/exports and (maybe) net energy flow

### ISSUE THREAD

**Issue by jacobbaratta** [corradio/electricitymap#371]
Right now when you select a country there's a listing of countries importing/exporting energy into or out of the country that's selected, shown as positive/negative bars on the bar graph. My suggestion is to add three more bars to the graph - a "total imports" bar (self explanatory), a "total exports" bar (self explanatory), and (maybe) a "total net energy flow" bar (the name is a bit clunky so maybe change it, but the basic idea is that this would display imports minus exports, although I'm not sure if it's necessary if you have the prior two).

I think this would be very interesting additional data to have available.

**Comment by corradio** [comment]
Hi @jacobbaratta 
Good point. We've already discussed this internally. Unfortunately it would be hard visually to understand that some bars are the sum of others.
I'll keep your suggestion in mind however, in case I find a nice solution.

**Comment by jacobbaratta** [comment]
@corradio Aren't text descriptions saying "Total imports:" and "Total exports:" pretty self-explanatory (especially since they'd lack the country flags)?

**Comment by corradio** [comment]
You're right, but that would also warrant adding "Total production" (so we're talking about 3 lines). I believe those numbers are not relevant for most of the visitors (who are not experts), and might clutter the view and weaken the value for non-experts.
We could think of adding it in the tooltip though.

**Comment by nikkozzblu** [comment]
Couldn t we just stack the bars that are currently displayed? With some colors by country it can do the job

Nico Juguet

-------- Mensaje original --------
Asunto: Re: [corradio/electricitymap] [Idea] Display aggregated total imports/exports and (maybe) net energy flow (#371)
De: Olivier Corradi
Para: corradio/electricitymap
CC: Subscribed


Hi @jacobbaratta<https://github.com/jacobbaratta>
Good point. We've already discussed this internally. Unfortunately it would be hard visually to understand that some bars are the sum of others.
I'll keep your suggestion in mind however, in case I find a nice solution.

**Comment by corradio** [comment]
Good idea! But I can't see how you would show which country corresponds to which portion of the bar if they are colored by co2? There might not be room for a label unfortunately.

**Comment by nikkozzblu** [comment]
Wider bars with flags inside ?
Or flags above ?

Nico Juguet

-------- Mensaje original --------
Asunto: Re: [corradio/electricitymap] [Idea] Display aggregated total imports/exports and (maybe) net energy flow (#371)
De: Olivier Corradi
Para: corradio/electricitymap
CC: nikkozzblu ,Comment


Good idea! But I can't see how you would show which country corresponds to which portion of the bar if they are colored by co2? There might not be room for a label unfortunately.

**Comment by corradio** [comment]
If you make bars wider you lose the ability to compare them to production.
If you add flags above, how do you visually link them to the (potentially
much smaller) bars?
