### ISSUE TITLE
Capacities of CZ, DE, Montenegro, Serbia

### ISSUE THREAD

**Issue by Martin281** [corradio/electricitymap#372]
Hallo, at first I would like to thank you for creation of such a wonderful tool as an online actual electriity map. It is great for comparison of the power systems of the countries. 
My Issue: As a citizen of Czech Republic I have double checked the info about it in your system:
I found out the wrong data about total output of power plants in this country, the corect ones are (based on the 2014 annual report of czech energy regulatory office) 
gas power plants: 1363,3MWe
nuclear power plants: 4290 MWe (increased due to higher efficiency of the electricity generator turbines)
hydro power plants: 1080,4 MWe
pumped storage hydro power plants: 1171,5 MWe
wind power plants: 278,1MWe
solar power plants: 2067,4 MWe
"coal" power plants: 10836,7 MWe (in this kind are included also power plants using the rest of fuel types - 4,8% of it is biomass, the "hardcore coal" is approx. 90% of the total power of this type)

**Comment by corradio** [comment]
Hi @Martin281 ,

Thanks for the issue. Are you talking about production capacities of each production mode?
Can you send us a link to the documentation you are referring to?

Thanks!

**Comment by Martin281** [comment]
Hi Olivier,
I foud out some new data..so sending the link to the 2015 annual report of this office in english: download here: http://www.uschovna.cz/en/zasilka/LI3CEN27SRWRBTPN-SNX/MAZ28SC3DC

Sincerely
Martin

**Comment by corradio** [comment]
Thanks!

**Comment by Martin281** [comment]
Hi Olivier,
I was looking for german annual report and here is it (in german language): https://www.bundesnetzagentur.de/SharedDocs/Downloads/DE/Sachgebiete/Energie/Unternehmen_Institutionen/DatenaustauschUndMonitoring/Monitoring/Monitoringbericht2016.pdf?__blob=publicationFile&v=2

The most important is page number 45 with all the capacities according to the type of fuel (mode) of energy generation.Explanations: nicht erneuerbare energieträger= not renewable fuel, erneuerbare energieträger= renewable fuel, braunkohle = brown coal, steinkohle = black coal, erdgas = natural gas, kernenergie=nuclear energy, pumpspeicher = hydro storage, mineralölprodukte = oil, sonstige = other, biomasse=biomass, laufwasser= hydro...), total outputs for each type are at the last row of the table. In the remark at the bottom is written that small power plants under 10MW are not included in this table (total output of all these plants  = 4297MW)
Sinceely
Martin

**Comment by corradio** [comment]
Thanks,

@brunolajoie can you double check the capacities for DE?
Here's the relevant page:

![image](https://cloud.githubusercontent.com/assets/1655848/22985242/30cfa8e6-f3a8-11e6-9490-7b44f4e56072.png)

**Comment by alixunderplatz** [comment]
Hi @corradio and @Martin281
I think regarding Germany, the aggregated data from [energy-charts/Fraunhofer](https://energy-charts.de/power_inst.htm) represent the most recent numbers.
Especially wind energy installations were high in 2016 and are included in their data, already. The chart above however shows installation capacity for the end of 2015. Not much has changed for conventional energy, though.

**Comment by Martin281** [comment]
ok, I think Germans are very accurate in statistics, so I think your data are up-to-date:o)
Sincerely 

Martin

**Comment by corradio** [comment]
Indeed! I didn't see the 2016 numbers are out. @brunolajoie can you update capacities with those?

**Comment by Martin281** [comment]
Hi Olivier,
I saw you have a lot of question-marks at the production capacities in the balkan countries...so to eliminate them..sending you the link to 2015 Annual report for Serbia..the only major discrepancy is in the total output of coal power plants..since the plants at the Kosovo area no longer belong to Serbia..here is the link: http://www.eps.rs/Eng/Tehnicki%20Izvestaji/TEHNICKI%20GODISNJAK%20WEB%202015%20E.pdf
The next is Montenegro...no actual annual report is available but the production capacities of Montenegro are described directly at the Montenegro electricity providing company here: http://www.epcg.com/en/about-us/production-facilities
Sincerely 

Martin

**Comment by corradio** [comment]
Thanks Martin.
Are you able to make a pull request with the required changes? I'm quite
busy and I won't have time to look at this :(

**Comment by Martin281** [comment]
OK, 

Serbia: 

coal power plants (TPP) :total power output 4,032GW
hydro power plants: total output 2,936GW
compined heat and power plants: total output 336MW
other kinds of power production are not used

Montenegro:

coal power plants (TPP) :total power output 218,5MW
hydro power plants: total output 649MW
other kinds of power production are not used

Sicerely

Martin

**Comment by brunolajoie** [comment]
Thanks guys!
I've updated the code in #381
I've used ENSTOE data (for consistency) when data looked correct, and your reports when they were better!
Don't hesitate to criticize!
Bruno

**Comment by corradio** [comment]
Re-opening because the PR hasn't been merged yet

**Comment by brunolajoie** [comment]
@corradio we can close this one now isn't it?

**Comment by corradio** [comment]
@brunolajoie it was closed on 28 Feb
