### ISSUE TITLE
Add Russia

### ISSUE THREAD

**Issue by zeynepnaz** [corradio/electricitymap#382]
Real time export-import data for Russia can be found under the following link.

http://www.statnett.no/en/Market-and-operations/

**Comment by corradio** [comment]
Hi @zeynepnaz ,

Indeed, but aren't they already on the map?

![image](https://cloud.githubusercontent.com/assets/1655848/23077576/6dbb342a-f545-11e6-8e63-33cb4cb8af2a.png)

**Comment by zeynepnaz** [comment]
There is no data in the version of map I am looking at.

**Comment by corradio** [comment]
Can you post a screenshot? And maybe the output of the developer console?

**Comment by zeynepnaz** [comment]
I couldn't download the docker on my computer, probably because of this I can't see the latest version.
Sorry my mistake. I will close the issue.

**Comment by corradio** [comment]
@zeynepnaz you need an ENTSOE token if you want to see the data.
Alternatively, when running locally, you can use remote data by doing http://localhost:8000/?remote=true
