### ISSUE TITLE
Update Lithuanian RES capacities

### ISSUE THREAD

**Issue by alixunderplatz** [corradio/electricitymap#384]
I just saw that Lithuanian wind generation was 113% of installed capacity.
I could find some fresh data (18th January 2017) here:
https://enmin.lrv.lt/en/sectoral-policy/renewable-energy-sources

> As of 18 January 2017, Lithuania has 2,566 power plants installed and holding permits to generate electricity from RES. Total installed capacity of these plants is 799.355 MW:
> 
> •    (2,263) solar plants – 72.54 MW;
> •    (153) wind plants (farms) – 498.906 MW;
> •    (12) solid biomass plants – 64.95 MW;
> •    (39) biogas plants – 35.05 MW;
> •    (99) hydro electric plants – 127.909 MW.

So these could be updated:
Solar: 73 MW
Wind: 499 MW
Biomass: 100 MW

Greetings, Alex

**Comment by corradio** [comment]
@brunolajoie can you take a look?
