### ISSUE TITLE
% fossil energy

### ISSUE THREAD

**Issue by Pauladdenda** [corradio/electricitymap#388]
The percentage of fossil energy should not include imports? Currently it is based on domestic production.

![image](https://cloud.githubusercontent.com/assets/25981441/23260137/b5b39440-f9d0-11e6-821a-5d1a88161d50.png)

**Comment by corradio** [comment]
That's true. 
@brunolajoie what do you think? Taking into account imports is complicating the matter, because imported power can be imported from the current country, so we need to solve a linear problem almost equivalent to the CO2 one, just with % fossil fuels instead of CO2.

**Comment by brunolajoie** [comment]
Nice catch@Pauladdenda ! I think, given the importance of this percentage, which for many speaks more than gCO2/kWh, that we should include this correction to our code. It is indeed a 100% strictly similar calculation process than that of CO2 intensity!

**Comment by Pauladdenda** [comment]
To solve your equation problems, it may be possible to ignore imports in your calculations (CO2 and%) for countries where the impact is very low. (I.e if the import is less than 5% of total production).
This will set some values to deduce the others. There will be a total mistake but will remain limited and lower than currently.

**Comment by brunolajoie** [comment]
The same remark would hold true for the CO2 intensity in gCO2/kWh as well, but we calculate it exactly. The easiest way for %fossil is to dupicate & adapt the CO2 intenstity calculation code.

**Comment by Pauladdenda** [comment]
Pour parler au plus grand nombre (je ne sais pas si le but), afficher le pourcentage de renouvelable peut également être intéressant. 
Les deux pourcentages ne feraient pas 100% : la différence représenterez les non renouvelable, non fossile : nucléaire et pompage principalement.

Actuellement, un non-initié va par exemple déduire que comme il y actuellement 14% de fossile en France les 86% restant sont renouvelable.

Une bulle d’aide permettrait de faire un peu de pédagogie sur la différence entre fossiles, renouvelables, et les autres.

**Comment by corradio** [comment]
I'm pushing a fix now:

Before:

![image](https://cloud.githubusercontent.com/assets/1655848/23366084/bff653a6-fd05-11e6-89af-eda8adefdbd1.png)

After:

![image](https://cloud.githubusercontent.com/assets/1655848/23366051/ac6f8bb8-fd05-11e6-978f-005834c89464.png)
