### ISSUE TITLE
Invalid capacities for Germany

### ISSUE THREAD

**Issue by Maverick78de** [corradio/electricitymap#390]
The data of max installed power capacities in Germany is wrong.

The maximum capacities are:
wind (onshore): 45.51GW
wind (offshore): 4.13GW
water: 5.59GW and not 12.9GW
biomass: 7.06GW
nuclear: 10.8GW
coal: 49.28GW
gas: 28.27GW
oil: 4.19GW
solar: 40.85GW

Source: BMWi and Bundesnetzagentur for year 2016
e.g. https://www.bundesnetzagentur.de/DE/Sachgebiete/ElektrizitaetundGas/Unternehmen_Institutionen/Versorgungssicherheit/Erzeugungskapazitaeten/erzeugungskapazitaeten-node.html

**Comment by corradio** [comment]
@brunolajoie can you take a look?

**Comment by brunolajoie** [comment]
Hello Maverick, thanks for your comment.

According to me, our data on the electricitymap matches the one you just wrote. Where did you see 12.9GW of hydro capacity? I read 5.59 on our map. Feel free to re-open if you still think there is a mistake on our side.

Best,
Bruno
