### ISSUE TITLE
Net imported/exported power addition 

### ISSUE THREAD

**Issue by cionetto** [corradio/electricitymap#402]
Hello everyone,
how about adding for each country the net balance between imported and exported power? 
E.g. UK is importing 2.05 GW from France, 1.01 GW from Netherlands and it's selling 172 MW to Northern Ireland and 232 MW to Ireland. Thus: 
Total Import: 3.06 GW
Total Export: 0.404 GW
Net Import/Export: +2.656 GW

**Comment by corradio** [comment]
I think we discussed it here: https://github.com/corradio/electricitymap/issues/371
Feel free to re-open if the answer is not satisfactory.
