### ISSUE TITLE
Error % combustibles fosiles

### ISSUE THREAD

**Issue by Pedlf** [corradio/electricitymap#404]
El dato del % de consumo de combustibles fósiles es erróneo porque la energía nuclear es un combustible fósil, y no queda reflejado en el %, contando como renovable que no es.

**Comment by nikkozzblu** [comment]
La fuente de nuclear es un mineral, no es fossil...

Tiene razón en lo que no es renovable, pero no creo que aparece como renovable en cualquiera parte del sitio

Nico Juguet

-------- Mensaje original --------
Asunto: [corradio/electricitymap] Error % combustibles fosiles (#404)
De: Pedlf
Para: corradio/electricitymap
CC: Subscribed


El dato del % de consumo de combustibles fósiles es erróneo porque la energía nuclear es un combustible fósil, y no queda reflejado en el %, contando como renovable que no es.

**Comment by ThierryOllivero** [comment]
Hola Pedfl,

La definicion de "Energia fosil" es "aquella que procede de la biomasa producida hace millones de años que pasó por grandes procesos de transformación hasta la formación de sustancias de gran contenido energético como el carbón, el petróleo, o el gas natural, etc"

Entonces la energia nuclear no es una energia fosil (gas, petroleo, carbon) y no es una energia renovable (eólica, geotérmica, hidroeléctrica, mareomotriz, solar...).
