### ISSUE TITLE
A best comparison

### ISSUE THREAD

**Issue by YANNCHAUSS** [corradio/electricitymap#405]
Hello,
it could be interresting to have the total product of electricity for each state ( at the instant ou for the current day)
Sorry for my poor english
Thank you 
Yann CHAUSSAVOINE

**Comment by corradio** [comment]
Bonjour Yann,

Parlez-vous d'avoir la production totale d'électricité par pays?

Olivier

**Comment by YANNCHAUSS** [comment]
Bonjour
Oui le total  instantan&eacute; ou le total sur 24H. Ou bien le total par habitant du pays
Il me semble que si ce chiffre apparait de fa&ccedil;on tr&egrave;s visible, il ajoute le poids de l'&eacute;lectricit&eacute; par rapport aux autres &eacute;nergies qui sont toutes fossiles
Cordialement
YC

----- Mail d'origine -----De: Olivier Corradi <notifications@github.com>&Agrave;: corradio/electricitymap <electricitymap@noreply.github.com>Cc: YANNCHAUSS <y.chaussavoine@laposte.net>, Author <author@noreply.github.com>Envoy&eacute;: Tue, 07 Mar 2017 20:03:58 +0100 (CET)Objet: Re: [corradio/electricitymap] A best comparison (#405)

Bonjour Yann,
Parlez-vous d'avoir la production totale d'&eacute;lectricit&eacute; par pays?
Olivier
&mdash;You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by corradio** [comment]
Bonjour Yann,

Nous devons constamment faire des choix sur le type d'information à monter, et il existe beaucoup d'indicateurs qui pourraient potentiellement être intéressants, mais qui entravent la lisibilité de la carte.
Nous n'avons pas jugé important le fait d'ajouter un total de production, car nous voulons plutot montrer l'impact carbone.

Cordialement,

Olivier
