### ISSUE TITLE
Clarification on per-country table

### ISSUE THREAD

**Issue by scottlee120** [corradio/electricitymap#45]
<img width="372" alt="screenshot 1" src="https://cloud.githubusercontent.com/assets/22021823/18317461/87df9d5c-751e-11e6-8789-497e2275d36e.png">

Are the bars at the bottom indicating energy exports/imports? i.e. is Germany exporting dirty coal power to France or importing power from France?

**Comment by corradio** [comment]
Positive means "locally available energy", or equivalently, "where does my energy come from" (from the consumer point of view).
Germany is therefore exporting energy to France (I believe this is the French panel).
