### ISSUE TITLE
Toogle layers/modes

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#47]
Submitted by Bruno:

I'm thinking out loud here, but what about having three ways for the reader to read this map, that could be accessed via three buttons on the top left:

CO2 focus (the default button): Displays your electricity map as it is now, without wind vectors

Wind focus: It displays wind vectors, and the country colored by GW of Wind power produced (shade of blue for instance)

Solar focus: It displays sun irradiance over Europe, and GW of solar power produced by country. Depending on what your datasource for solar irradiance look like, I see two options:
3.1: Solar irradiance as lines of iso irradiance and solar power as shade of yellow over the country area
3.2: or Solar irradiance as shades of yellow over the hole europe map, and solar power per country as a textured fill of black dots (the densier the dots, the more GW).

**Comment by rgieseke** [comment]
+1 on this

Would be great to be able to disable the wind animation as it makes my fan spin (and thus likely to close the tab) ...
It's quite useful and interesting without this I'd think and it would be nice to leave the tab open and come back to check for changes.

**Comment by corradio** [comment]
Summing up, it would make sense to be able to
- [ ] show / hide solar data
- [ ] show / hide wind data
- [ ] show / hide import - export
- [ ] show emissions per capita

**Comment by martindaniel4** [comment]
An idea I had yersteday was to combine the legend with the toggle.

Ugly sketch below : 

![legend_map](https://cloud.githubusercontent.com/assets/695006/20317880/c845559c-ab1c-11e6-9b9c-d554ae8d9850.png)

**Comment by corradio** [comment]
For now you can use http://electricitymap.tmrow.co/?wind=false

**Comment by corradio** [comment]
Data is now ready on the backend. We need to design the changes.
I love @martindaniel4 's idea of using the legend as toggle. We should locate it in the bottom of the left panel where the introductory text is located.

**Comment by corradio** [comment]
I'm playing around with this idea:

![image](https://cloud.githubusercontent.com/assets/1655848/21355138/21985f60-c6cd-11e6-862f-ed3bbc4f20cc.png)

**Comment by corradio** [comment]
Discussed with Thierry - we're trying to use a checkbox system instead.

**Comment by corradio** [comment]
Merged a first version.
