### ISSUE TITLE
No thumbnail shown when sharing on social media

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#54]
@guicoelho do you have a clue as to why?

**Comment by guicoelho** [comment]
PR #57 fixes this.

**Comment by corradio** [comment]
It still doesn't work with Facebook:
![image](https://cloud.githubusercontent.com/assets/1655848/18623545/e689d2cc-7e3e-11e6-97e5-9c89f413934b.png)
Twitter shows no preview at all :(

**Comment by corradio** [comment]
Using https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Felectricitymap.tmrow.co to troubleshoot

**Comment by corradio** [comment]
Fixed for FB. App id was missing and there was an unknown character in the DOCTYPE tag.

**Comment by corradio** [comment]
Now debugging twitter with https://cards-dev.twitter.com/validator

**Comment by corradio** [comment]
GG for Twitter!
![image](https://cloud.githubusercontent.com/assets/1655848/20170496/c22e812c-a72c-11e6-948c-0dc715f68fbd.png)
