### ISSUE TITLE
Experiment with fixed power and co2 scale in the country panel

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#61]
Could this yield a better comparability between countries? Or would it kill the signal?

**Comment by scottlee120** [comment]
What would this look like?

**Comment by corradio** [comment]
It would mean that the power scale (horizontal) would have a max which is set to the max of all countries (and thus it's constant across countries) instead of being the max for this particular selected country.
![image](https://cloud.githubusercontent.com/assets/1655848/18588879/91992398-7c28-11e6-9584-87d9e2381b74.png)

**Comment by scottlee120** [comment]
Might be too much work - Portugal and Germany are going to be magnitudes apart on such a scale and it might just confuse the signal unless you can find a perfect number that fits all of them somehow

**Comment by corradio** [comment]
That's what I thought too when I initially chose the scale.
