### ISSUE TITLE
Add Feature/Hungary

### ISSUE THREAD

**Issue by ThierryOllivero** [corradio/electricitymap#65]
Data will be retrieved from : http://www.mavir.hu/web/mavir-en/transparency

**Comment by corradio** [comment]
Actually it's pretty annoying because they return an image. We can't get their raw data.

![image](https://cloud.githubusercontent.com/assets/1655848/18670117/91f887de-7f3e-11e6-8588-5e01a310856a.png)

The only way is unfortunately to contact them.

**Comment by ThierryOllivero** [comment]
Above the image, there is a way to export the data as XLS. Maybe there is a way to retrieve the data there...

**Comment by corradio** [comment]
Indeed good idea. Seems like there's 15min data.

We just need to translate the headers. Then I can write an XLS parser:

Erőművi szumma term. tip. net.mérés (15p)
Nukleáris erőművek net.mérés (15p)
Barnakőszén-lignit erőművek net.mérés (15p)
Gáz (fosszilis) erőművek net.mérés (15p)
Feketekőszén erőművek net.mérés (15p)
Szárazföldi szélerőművek net.mérés (15p)
Biomassza erőművek net.mérés (15p)
Naperőművek net.mérés (15p)
Szemétégető erőművek net.mérés (15p)
Folyóvizes erőmvek net.mérés (15p)
Víztározós vízerőművek net.mérés (15p)
Olaj (fosszilis) erőművek net.mérés (15p)
Egyéb megújuló erőművek net.mérés (15p)
Egyéb erőművek net.mérés (15p)

**Comment by ThierryOllivero** [comment]
Erőművi szumma term. tip. net. mérés (15p) - Total Production
Nukleáris erőművek net.mérés (15p) - Nuclear
Barnakőszén-lignit erőművek net.mérés (15p) - Lignite (Coal)
Gáz (fosszilis) erőművek net.mérés (15p) - Gas
Feketekőszén erőművek net.mérés (15p) - Coal
Szárazföldi szélerőművek net.mérés (15p) - Wind
Biomassza erőművek net.mérés (15p) - Biomass
Naperőművek net.mérés (15p) - Solar
Szemétégető erőművek net.mérés (15p) - Incineration (Biomass ?)
Folyóvizes erőmvek net.mérés (15p) - Hydro
Víztározós vízerőművek net.mérés (15p) - Hydro
Olaj (fosszilis) erőművek net.mérés (15p) - Fioul 
Egyéb megújuló erőművek net.mérés (15p) - Other Renewables
Egyéb erőművek net.mérés (15p) - Other non Renewables

**Comment by corradio** [comment]
Link to Excel is 
http://rtdwweb.mavir.hu/webuser/ExportChartXlsIntervalServlet?fromDateXls=2016-09-20&fromTimeXls=T15%3A00%3A00&toDateXls=2016-09-21&toTimeXls=T16%3A00%3A00&resoulutionInput=15&unit=min&outputType=XLS&selectedTabId=tab9405&submitXls=
We just need to replace with the proper dates. Will write a parser.

**Comment by corradio** [comment]
@ThierryOllivero if you find the same information for import/export then I can integrate it
