### ISSUE TITLE
Add Feature/Czech Republic

### ISSUE THREAD

**Issue by ThierryOllivero** [corradio/electricitymap#71]
Data for generation can be found here: http://www.ceps.cz/ENG/Data/Vsechna-data/Pages/Vyroba.aspx

Possibility to export in TXT, XLS or XML. I guess there is also a way to retrieve them from the script behind the graph. 

Data for exports / imports are here: http://www.ceps.cz/ENG/Data/Vsechna-data/Pages/Preshranicni-toky.aspx

Same thing, export in TXT, XLS or XML or from the data behind the graph.

**Comment by corradio** [comment]
I'm taking a look now.
cc @scottlee120.

**Comment by corradio** [comment]
I need help in figuring out what those are / what fuel powers:

- Alternative Power Plant - AltPP
- Thermal Power Plant - TPP
- Autoproducer Power Plant - ApPP

**Comment by ThierryOllivero** [comment]
Autoproducer does not exist any more.

By cross checking with ENTSO-E: 

- Thermal : Coal (Lignite 85%, hard coal 15%)
- Alternative : Biomass + Waste

**Comment by corradio** [comment]
Thanks Thierry! Can you send the link here for reference? Then I'll add it

On Wed, Sep 21, 2016 at 10:34 AM, Thierry Ollivero <notifications@github.com

**Comment by ThierryOllivero** [comment]
Sure, there you go: https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=21.09.2016+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=21.09.2016+00:00|CET|DAYTIMERANGE&area.values=CTY|10YCZ-CEPS-----N!BZN|10YCZ-CEPS-----N&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
