### ISSUE TITLE
Add Feature/Poland

### ISSUE THREAD

**Issue by scottlee120** [corradio/electricitymap#73]
See if we can fill out Poland - I discovered this page: http://www.pse.pl/index.php?modul=21&id_rap=30

It's in PL only but with Google Translate enabled you can figure out the basics - it's a start if nothing else as the Poles also provide some live data from the TSO just in PL only. 

Also in case of more info needed on basic capacity by source: http://www.paiz.gov.pl/files/?id_plik=19610

**Comment by scottlee120** [comment]
I have no idea how to tag this as an enhancement... :(

**Comment by corradio** [comment]
To the right, under "Labels"

**Comment by corradio** [comment]
Seems like we lack information as to the production mix?

**Comment by scottlee120** [comment]
I actually can’t modify that :(

**Comment by scottlee120** [comment]
Yup - except for wind. The Poles provide wind production info.
