### ISSUE TITLE
Border Color

### ISSUE THREAD

**Issue by ThierryOllivero** [corradio/electricitymap#74]
When two countries are black, the border between them because invisible.

![image](https://cloud.githubusercontent.com/assets/22315693/18705180/7252638c-7fed-11e6-964d-612724bff953.png)

Quick fix: Change border color to white for all countries, all the time.
Or: Change border color only between countries that are both black at a given time (requires coding)

**Comment by corradio** [comment]
This is with a white background:

![image](https://cloud.githubusercontent.com/assets/1655848/18705511/d816493a-7fee-11e6-9dc4-b3091db204cd.png)

**Comment by guicoelho** [comment]
Using the same color as the blue-grey used for the ocean could also work

**Comment by ThierryOllivero** [comment]
Yes, white was only a suggestion.

**Comment by corradio** [comment]
Super light gray (#999999):
![image](https://cloud.githubusercontent.com/assets/1655848/18705655/52ef7dca-7fef-11e6-9199-f23a54e1acff.png)

Graticule blue (#185c96):
![image](https://cloud.githubusercontent.com/assets/1655848/18705678/67b31a0a-7fef-11e6-8376-9e09550f41b2.png)

**Comment by guicoelho** [comment]
Also don't like it in blue actually

**Comment by corradio** [comment]
So go for the gray version?

**Comment by ThierryOllivero** [comment]
Don't know. With the grey you don't see the border between countries for which we don't have data.

White is not good?

**Comment by corradio** [comment]
@guicoelho @scottlee120  WDYT? Which one is your preferred version?
Seems like @ThierryOllivero prefers white. Let's just decide this by voting :)

**Comment by scottlee120** [comment]
White for me as well - it’s higher contrast than gray i think

**Comment by corradio** [comment]
I think I found a good balance. I took a gray which is slightly darker than the default country fill:

![image](https://cloud.githubusercontent.com/assets/1655848/18708479/477c984a-7ffb-11e6-8ac6-4fb2c63f7a36.png)

**Comment by ThierryOllivero** [comment]
I think we can move on with this color @corradio. Let me know when the change is merged, so I can close the issue.
