### ISSUE TITLE
PT data is two days old

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#76]
Right we are 
"2016-09-21T12:23:00.000Z"

and the last data is from
"2016-09-19T23:00:00.000Z"

Something seems to be wrong in the parser.

**Comment by guicoelho** [comment]
I just ran the parser and it shows data from 2016-09-20:

![image](https://cloud.githubusercontent.com/assets/4061341/18719273/ff239928-8026-11e6-89da-085259173914.png)

What else could it be?

**Comment by corradio** [comment]
2016-09-20 at 00:00 UTC+1 is the same as 2016-09-19 23:00 UTC. So we have the same datetime. But shouldn't we grab the data point at 2016-09-21 00:00 in this example?
Or maybe the datetime you grab is the date of the *start* of the day (so the datetime we should register is 24h after, because we take the average for that day, once it's over)

**Comment by guicoelho** [comment]
Yes, I'm only taking the date, the time is just 0,0,0 because those are the default values in the python lib that creates the datetime object.

Maybe what makes more sense is to set the time to 12:00... so, middle of the day since the data is an average of that day.

**Comment by corradio** [comment]
if the data is the average of the day then the average can only be computed
at the end of the day.
Therefore I suggest that we set the datetime at the end of the day, because
that's the earliest time at which you can actually compute an average.
I've been doing it that way every time I had a time interval. We could
challenge this though, but I think we have to stay consistent.

**Comment by guicoelho** [comment]
Fine for me!
