### ISSUE TITLE
[CO2API] Calculations are wrong when production is < 0

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#86]
http://electricitymap-api.tmrow.co/v1/co2?countryCode=CZ

Response results in a wrong co2 intensity:

![image](https://cloud.githubusercontent.com/assets/1655848/19192267/fe76502a-8ca5-11e6-86b1-b945d1b28f0f.png)

This is probably due to the fact that some production values are negative. We should always cap them to be at least 0.
Needs update in https://github.com/corradio/electricitymap/blob/master/api/server.js#L115

@scottlee120 want to take a look?

**Comment by scottlee120** [comment]
Sure - taking a look now + tomorrow!

**Comment by corradio** [comment]
Thanks Scott for fixing the bug via https://github.com/corradio/electricitymap/commit/273382e51525834df356d235913ee051035cda3b
