### ISSUE TITLE
[FEEDER] RO.py ValueError

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#87]
```
fetch_one_country()
Traceback (most recent call last):
  File "feeder.py", line 51, in fetch_countries
    obj = parser()
  File "/home/parsers/RO.py", line 20, in fetch_RO
    'unknown': float(data['CONS'])
ValueError: could not convert string to float: #N/A
```

**Comment by scottlee120** [comment]
@corradio : how do i reproduce this? i tried running python feeder/feeder.py but that doesn't work

**Comment by corradio** [comment]
`python feeder/parsers/RO.py` but it only will make the error if you happen
to have a consumption value equal to NA

**Comment by scottlee120** [comment]
Is there a way I can force the NA/error state for testing purposes then?

All the best,
Scott

Sent from my iPhone

12 окт. 2016 г., 18:32 +0200, Olivier Corradi <notifications@github.com>, писал:

**Comment by corradio** [comment]
I think you need to add a line that assigns the value to that variable -
that's the only way.

**Comment by corradio** [comment]
@scottlee120 any news here?

**Comment by scottlee120** [comment]
Nope - haven't looked at this weekend. If it's urgent, feel free to assign it to someone else as I won't have much time this week in any case

Best,
Scott

17 окт. 2016 г., 13:02 +0200, Olivier Corradi <notifications@github.com>, писал:
