### ISSUE TITLE
biomass carbon intensity should be put to 230

### ISSUE THREAD

**Issue by brunolajoie** [corradio/electricitymap#89]
CO2 emissions from biomass harvesting should not be accounted at the power plant, reducing lifecycle emissions of biomass power from currently ~740gCO2eq/kWh to 230 (min 130 max 420), as per IPCC estimates.

**Comment by corradio** [comment]
So we should probably use 230 as per https://en.wikipedia.org/wiki/Life-cycle_greenhouse-gas_emissions_of_energy_sources#2014_IPCC.2C_Global_warming_potential_of_selected_electricity_sources right?

**Comment by ThierryOllivero** [comment]
Since we use some Supply Chain data for all (Solar, Wind, Hydro), we should do the same for biomass. Therefore 230.

**Comment by corradio** [comment]
@brunolajoie do you confirm?

**Comment by brunolajoie** [comment]
Yes, I think 230 is the central estimate that we should use, a least wrong estimate as long as we can't dig further into the origin of the biomass harvested.

**Comment by corradio** [comment]
@brunolajoie @ThierryOllivero can one of you make the correction? Feel free to assign yourself to the issue if you work on this. Thanks!

**Comment by brunolajoie** [comment]
Not sure I can assign an issue to someone as a non admin user. But will correct and close the issue anyway!

**Comment by ThierryOllivero** [comment]
The question was more: "do you want to change the CO2eq.js", commit and pull request, or should I do it ?
