### ISSUE TITLE
Change country color scale so that 100% coal = black

### ISSUE THREAD

**Issue by brunolajoie** [corradio/electricitymap#92]
Green = 0gCO2eq/kWh
Black = 820gCO2eq/kWh

**Comment by corradio** [comment]
Sounds reasonable. I'll post a screenshot with the two scales when I get the time.

**Comment by corradio** [comment]
[0, 250, 500]:
![image](https://cloud.githubusercontent.com/assets/1655848/19489353/3a069262-956b-11e6-997a-c447f40f25a3.png)

[0, 400, 800]:
![image](https://cloud.githubusercontent.com/assets/1655848/19489336/29758c6e-956b-11e6-958d-ea06bdb9959b.png)

**Comment by ThierryOllivero** [comment]
It is more colorful, but it seems everyone is doing not too bad. 

Pros : more nuances between DE and CZ, ET, PT. 

Cons : no one will ever be black again.

Could you show what it would be with 700 as black?

**Comment by brunolajoie** [comment]
I suggest that @corradio look at the history of CO2 intensity of each country, and set the black color to the maximum level ever reached. It should be close to 700 indeed

**Comment by corradio** [comment]
700:
![image](https://cloud.githubusercontent.com/assets/1655848/19511045/e5e09d56-95e5-11e6-9a81-928b81cb1443.png)

600:
![image](https://cloud.githubusercontent.com/assets/1655848/19511055/f4893674-95e5-11e6-8c59-10c6c446a762.png)

**Comment by ThierryOllivero** [comment]
700 seems fair. It means at least 80% coal + other dirty ways of generating or 90% coal and clean ways of generating. Black enough for me.

The screenshot for 700 shows a lot of nuances.

**Comment by corradio** [comment]
I prefer 600, but no strong opinion. @brunolajoie what do you think?

**Comment by brunolajoie** [comment]
I agree!

**Comment by brunolajoie** [comment]
i mea

**Comment by corradio** [comment]
700 it will be. Keep the issue open because it hasn't been fixed yet! I only showed you a preview. I'll close the issue when it is published
