### ISSUE TITLE
[FEEDER] Production from ENTSOE

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#94]
@Pantkowsky started looking into this. Can we use your existing table to list each country and mark whether ENTSOE is better than what we already have (it will always be better if we have nothing at the moment)?

**Comment by ThierryOllivero** [comment]
I'll look at it from my computer later today, but I seem to recall that for some countries there are several "nodes" to select. Not sure if node is the right word though.

**Comment by Pantkowsky** [comment]
@corradio sure, no problem
@ThierryOllivero correct, some countries have few or several areas to obtain the data from. For Italy it may change things, as I did not check every single area (there are like 15 of them), but for Ukraine for example there were 3 and none of these returned any information. Same for Russia and some other countries.
@corradio I agree that ENTSOE will be better if it provides at least something for a country that we don't have on the map yet. In that case of course, we should get the info from ENTSOE. I'm wondering about other, with UK being the obvious example. Comparing the data from ENTSOE and from the sources we are already using would be a smart thing to do. Maybe we could even combine them?

**Comment by corradio** [comment]
If we get an overview then we can study countries for which there is both our own data and ENTSOE and see what we do.

**Comment by corradio** [comment]
Closing because should have a more detailed "task"
