### ISSUE TITLE
[FEEDER] PL: IndexError: list index out of range

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#95]
I get a lot of those errors:

```
Traceback (most recent call last):
  File "feeder.py", line 51, in fetch_countries
    obj = parser()
  File "/home/parsers/PL.py", line 29, in fetch_PL
    output_array = map(fetchValue, parameters)
  File "/home/parsers/PL.py", line 21, in fetchValue
    last = soup.find_all('point')[-1].find_all('quantity')[-1]
IndexError: list index out of range
```

@Pantkowsky can you try to take a look as to why it is caused? Maybe we're doing something wrong?

**Comment by Pantkowsky** [comment]
yeah, thats the error I get when I'm calling for some parameters from ENTSOE. We are trying to get the last value provided during the last 24h timeframe and it returns the error. Thats why I think that some of the parameters do not return any value, as maybe entsoe does not have the information about the one ? I will try to get something more concrete than speculation

**Comment by corradio** [comment]
A good place to start would be to show the whole xml output to make sure we're not missing anything.
